import type { DailyTaskTemplate } from './dailyTaskTypes'

/**
 * 365 道精选情侣每日任务题库（一年 365 天，每天一道专属任务）
 * 涵盖 10 大维度：表达、猜测、回忆、照片、小问题、共同完成、观察、分享、趣味挑战、专注陪伴
 * 涵盖 6 种任务类型：interaction, question, photo, focus, memory, random
 * 相邻日期严格交替不同任务类型，确保一年 365 天天天不同、永不重样！
 */
export const DAILY_TASK_POOL: DailyTaskTemplate[] = [
  {
    id: 'dt_001',
    title: '给对方发一句不能超过 10 个字的话',
    description: '字数很短，但装满了想念。试着用最简练的字句打动 TA 吧。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '例如：今天也很喜欢你。 / 晚上想和你吃面。',
  },
  {
    id: 'dt_002',
    title: '告诉对方今天最开心的一件小事',
    description: '哪怕只是吃到了好吃的面包，或者看到了一只可爱的云朵。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '写下今天让你嘴角上扬的一瞬间…',
  },
  {
    id: 'dt_003',
    title: '拍一张你现在眼前看到的东西',
    description: '不用刻意摆拍，把生活此刻的真实切片分享给对方。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '桌上的水杯、窗外的街道、手边的一本书…',
  },
  {
    id: 'dt_004',
    title: '一起完成 20 分钟专注陪伴',
    description: '各自忙碌，互相陪伴。在小窝里开启一段专注时光。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '去专注页面开启 20 分钟专注吧。',
  },
  {
    id: 'dt_005',
    title: '翻出一张你们刚在一起时的老照片',
    description: '还记得那天的天气和心情吗？把旧回忆重新温热一遍。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '描述那张照片的故事，或者去照片墙温习。',
  },
  {
    id: 'dt_006',
    title: '给对方起一个今天限定的可爱外号',
    description: '只限今天使用！可以很搞怪、很甜、或者很无厘头。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '例如：今日份小面包 / 宇宙第一瞌睡虫',
  },
  {
    id: 'dt_007',
    title: '猜猜对方今天最想吃什么',
    description: '默契大考验！先写下你的猜测，看看等会儿能不能对上答案。',
    task_type: 'question',
    action_type: 'input',
    category: '猜测',
    prompt_hint: '写下你猜 TA 今天最馋的美食…',
  },
  {
    id: 'dt_008',
    title: '在各自的地方喝一杯温水，给身体充充电',
    description: '天冷天热都要照顾好自己。喝完后点一下完成，把关心送达。',
    task_type: 'interaction',
    action_type: 'done',
    category: '共同完成',
    prompt_hint: '温水入喉，记得深呼吸一下哦。',
  },
  {
    id: 'dt_009',
    title: '拍一张今天的天空或窗外的光景',
    description: '即使在不同的地方，也能看着同一片天空。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '阳光、晚霞、细雨或是夜空都可以。',
  },
  {
    id: 'dt_010',
    title: '用三个词形容你眼里的对方',
    description: '在你的心里，TA 是什么样的存在呢？真诚地写下来吧。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '例如：温暖、善良、爱吃醋。',
  },
  {
    id: 'dt_011',
    title: '告诉对方你第一次对 TA 心动的瞬间',
    description: '可能是某次回眸、某句话、或者一个微小的动作。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '写下那个让你小鹿乱撞的瞬间…',
  },
  {
    id: 'dt_012',
    title: '如果可以立刻拥有一项超能力，你最想选什么？',
    description: '瞬间移动到对方身边？还是让时间变慢？聊聊天马行空的脑洞。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '写下你的超能力愿望和原因…',
  },
  {
    id: 'dt_013',
    title: '给对方推荐一首你今天单曲循环的歌',
    description: '戴上耳机，让对方也能听到你耳朵里的旋律。',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '歌名 + 一句最喜欢的歌词。',
  },
  {
    id: 'dt_014',
    title: '放下手机专注深呼吸 3 分钟，放松紧绷的双肩',
    description: '闭上眼睛，慢慢吸气吐气。两个人一起给大脑放个小假。',
    task_type: 'focus',
    action_type: 'done',
    category: '共同完成',
    prompt_hint: '做完三次深呼吸后，点击完成打卡。',
  },
  {
    id: 'dt_015',
    title: '拍一张身边带有黄色或粉色的小物品',
    description: '在身边的角落里寻找充满生机的颜色吧。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '文具、杯子、水果、花朵都可以。',
  },
  {
    id: 'dt_016',
    title: '猜猜对方现在正在做什么小动作',
    description: '在摸下巴？在发呆？还是在悄悄看手机？写下你的第六感。',
    task_type: 'question',
    action_type: 'input',
    category: '猜测',
    prompt_hint: '写下你脑海中 TA 此时此刻的画面…',
  },
  {
    id: 'dt_017',
    title: '给对方发一个你觉得最像 TA 的 Emoji',
    description: '可以是一只小动物、一个表情、或者一样奇怪的蔬菜。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '输入 1~3 个 Emoji 字符。',
  },
  {
    id: 'dt_018',
    title: '回忆一件你们一起经历过的爆笑糗事',
    description: '想起来依然会忍不住笑出声的回忆，才是最棒的调味剂。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '写下那件让你们笑到肚子痛的往事…',
  },
  {
    id: 'dt_019',
    title: '拍下你今天吃的美食或喝的饮品',
    description: '好好吃饭是头等大事，把美味也打包发给 TA 瞧瞧。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '早餐、午饭、下午茶或宵夜都可以。',
  },
  {
    id: 'dt_020',
    title: '互相问一个从来没有问过对方的小问题',
    description: '即使再熟悉的两个人，也总有一片神秘的小宇宙等待发现。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '写下你想问 TA 的那个好奇问题…',
  },
  {
    id: 'dt_021',
    title: '在各自的地方，拍一张手比半颗心的照片',
    description: '隔空拼成一颗完整的心，我们虽然不在一起，但心是在一起的。',
    task_type: 'photo',
    action_type: 'photo',
    category: '共同完成',
    prompt_hint: '伸出手比半颗心，拍下它。',
  },
  {
    id: 'dt_022',
    title: '给对方留一句今天最想听到的鼓励',
    description: '也许对方今天有点累，你的鼓励会成为 TA 最好的解药。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「今天辛苦啦，你是最棒的！」',
  },
  {
    id: 'dt_023',
    title: '闭上眼睛盲打一句给对方的话',
    description: '闭上眼睛在输入法上快速打一句话，看看会自动纠错成什么搞笑内容。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '不要偷看键盘，直接打出来！',
  },
  {
    id: 'dt_024',
    title: '一起完成 15 分钟阅读或专注',
    description: '放下短视频，读几页书或整理桌面，安安静静度过 15 分钟。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '开启专注，或者安静做一件事后点击完成。',
  },
  {
    id: 'dt_025',
    title: '说出对方身上的一个你很欣赏的好习惯',
    description: '真诚地发现对方的闪光点，夸夸对方吧！',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '细心、守时、热爱生活、还是脾气温和？',
  },
  {
    id: 'dt_026',
    title: '拍一张你现在桌面上最显眼的一样东西',
    description: '看看对方的桌子此刻是整整齐齐还是堆满了可爱杂物。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '拍下桌面的小角落。',
  },
  {
    id: 'dt_027',
    title: '分享一句对方曾经说过让你记到现在的暖心话',
    description: '有些话像冬日里的暖炉，一直温暖着后来的很多日子。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那句话是什么时候对你说的？',
  },
  {
    id: 'dt_028',
    title: '用对方平时最常用的口头禅或语气词打个招呼',
    description: '学对方说话，看看对方能不能立刻认出这是谁的语气。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '模仿 TA 平时撒娇或习惯的口头禅。',
  },
  {
    id: 'dt_029',
    title: '发现身边一件今天之前从来没注意过的小细节',
    description: '放慢脚步，观察平时忽略掉的世界，然后讲给 TA 听。',
    task_type: 'interaction',
    action_type: 'input',
    category: '观察',
    prompt_hint: '墙角的小影子、新冒出的绿芽、路边的小猫…',
  },
  {
    id: 'dt_030',
    title: '如果明天突然多出一天假期，你最想和对方做什么？',
    description: '赖床睡到自然醒、去看一场电影、还是漫无目的地散步？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '写下你心中的满分假期约会…',
  },
  {
    id: 'dt_031',
    title: '拍下你今天穿的鞋子或袜子',
    description: '一步一步踏踏实实走过来的路，也有 TA 在心底陪伴。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '低头拍一张脚下的风景。',
  },
  {
    id: 'dt_032',
    title: '猜猜对方今天听的第一首歌是什么风格',
    description: '是欢快的流行乐、安静的民谣、还是提神的摇滚？',
    task_type: 'question',
    action_type: 'input',
    category: '猜测',
    prompt_hint: '写下你的猜测，晚点一起对答案。',
  },
  {
    id: 'dt_033',
    title: '在同一分钟给对方发送一条哔卟提醒',
    description: '两个人约定一个整点或心有灵犀的瞬间，一起按下哔卟！',
    task_type: 'interaction',
    action_type: 'done',
    category: '共同完成',
    prompt_hint: '按下首页的 BIBU！大按钮发送心意。',
  },
  {
    id: 'dt_034',
    title: '分享一个最近被种草的宝藏小物件或好店',
    description: '把你想和 TA 一起体验的新鲜事物记进小账本。',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '一本书、一款零食、一家想打卡的小店。',
  },
  {
    id: 'dt_035',
    title: '说出你们一起去过最难忘的一个地方',
    description: '那个地方的风、那天的笑声，都是两个人专属的印记。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '写下地名和那天最深刻的细节。',
  },
  {
    id: 'dt_036',
    title: '睡前放下手机 10 分钟，放空思绪',
    description: '给眼睛和大脑一段安静的呼吸时间，带着轻松的心情入眠。',
    task_type: 'focus',
    action_type: 'done',
    category: '专注陪伴',
    prompt_hint: '放下屏幕后，放松片刻，点击完成。',
  },
  {
    id: 'dt_037',
    title: '拍下一件身边让你觉得很可爱的圆形物品',
    description: '圆滚滚的东西总能治愈心情，找找你身边有什么可爱的圆。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '纽扣、橘子、时钟、圆圆的抱枕…',
  },
  {
    id: 'dt_038',
    title: '如果用一种天气形容对方，你觉得是什么？',
    description: '春日暖阳、微风细雨、还是夏日晴空？聊聊你的感受。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '写下你心中属于 TA 的天气。',
  },
  {
    id: 'dt_039',
    title: '给对方发一句只有你们两个人能听懂的暗号',
    description: '情侣之间总有专属的暗号和梗，今天再用一次吧！',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '只有你们知道含义的那句悄悄话。',
  },
  {
    id: 'dt_040',
    title: '分享今天看到的任何一个好玩的新闻或搞笑表情包',
    description: '快乐是会传染的，把今天的笑点传递给 TA。',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '简短描述一下那个好玩的事。',
  },
  {
    id: 'dt_041',
    title: '找出一件对方送过你的小礼物，拍张照或写下名字',
    description: '每一件礼物都是当时用心的证明，现在还保存得好好的吗？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那份礼物是什么？你现在还常常用它吗？',
  },
  {
    id: 'dt_042',
    title: '一起完成 20 分钟专注学习或工作',
    description: '两个人在一起最好的状态，是一起向前走，各自闪闪发光。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '去专注模式开启 20 分钟计时。',
  },
  {
    id: 'dt_043',
    title: '给对方发一段真诚的夸奖（至少 20 个字）',
    description: '不要吝啬你的赞美，认真的肯定最能让人心里暖暖的。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '写下你想真诚夸奖 TA 的地方…',
  },
  {
    id: 'dt_044',
    title: '拍一张你现在的影子或手部特写',
    description: '光影里的剪影也很有艺术感，记录下光线给你的印记。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '阳光下的影子或比耶的手势。',
  },
  {
    id: 'dt_045',
    title: '两个人商量并定下一个周末想一起做的小心愿',
    description: '给生活一点期待感，周末一起去实现它吧！',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '例如：去公园散步 / 一起做顿晚餐 / 去看展。',
  },
  {
    id: 'dt_046',
    title: '拍一张今天喝的第一杯水、咖啡或奶茶',
    description: '早晨的第一口温润，拍下来给对方看看你今天的能量来源。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '咖啡杯、保温杯、或是冒着热气的马克杯…',
  },
  {
    id: 'dt_047',
    title: '夸夸卡：说出对方今天最迷人的一个细节',
    description: '不用华丽辞藻，发现 TA 身上微小却闪闪发光的优点。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '专注做事的神态、温柔的语气、或是好看的笑容…',
  },
  {
    id: 'dt_048',
    title: '盲打告白：闭上眼睛盲打「今天超级想你」，看看变成了什么搞笑文字',
    description: '完全不看屏幕快速敲击键盘，看看拼音输入法会自动纠错出什么奇葩内容。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '直接发出来，绝不许偷偷修改！',
  },
  {
    id: 'dt_049',
    title: '回忆第一次牵手时的温度和当时紧张的心跳细节',
    description: '那只试探着伸过来的手，手心里微微的汗意，你还记得吗？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '走在哪条路上？当时周围的灯光和声音是什么样的？',
  },
  {
    id: 'dt_050',
    title: '20 分钟并肩阅读',
    description: '各自翻开一本书，享受纸页翻动的宁静，用文字丰盈内心。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '开启专注模式，读完 10 页书。',
  },
  {
    id: 'dt_051',
    title: '假如时光倒流：回到我们第一次见面的那天，你想对自己说什么？',
    description: '站在上帝视角回头看，你会给当时懵懵懂懂的自己支什么招？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '「别紧张，站在你对面的那个人，就是你未来的命中注定！」',
  },
  {
    id: 'dt_052',
    title: '拍拍窗外此时天空的颜色',
    description: '无论阴晴，此刻的光线也是两个人共享的一抹风景。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '早晨的晨光、正午的蓝天或是傍晚的暮色。',
  },
  {
    id: 'dt_053',
    title: '感谢卡：谢谢对方最近为你做的一件贴心小事',
    description: '把那些原本习惯了的照顾，郑重地说一声谢谢。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '帮忙点的外卖、睡前的叮嘱、或是及时的安慰。',
  },
  {
    id: 'dt_054',
    title: 'Emoji 密电：只用 4 个 Emoji 表情讲一个今天发生的小故事，让 TA 猜',
    description: '不用任何文字，看看你们两个人的脑回路是不是在同一个奇妙频道上。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '例如：☕️🚶🌧️🏠，猜猜今天经历了什么？',
  },
  {
    id: 'dt_055',
    title: '翻翻相册，找到一张去年或前年这个时候我们在做什么的照片',
    description: '时间的刻度在相册里静静沉淀，看看一年前的我们是什么模样。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '翻出那张旧照片，对比一下现在的变化。',
  },
  {
    id: 'dt_056',
    title: '15 分钟桌面整理',
    description: '把眼前的工作台或书桌擦拭干净，物品归位，眼前清爽心情自好。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '清空桌面杂物，擦干净桌子。',
  },
  {
    id: 'dt_057',
    title: '恋爱默契：如果我们在孤岛上，你觉得我们俩谁的求生技能更强？',
    description: '荒野求生小脑洞，一个负责搭建营地，一个负责寻找浆果！',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '谁方向感更好？谁动手能力更强？聊聊分工合作。',
  },
  {
    id: 'dt_058',
    title: '拍一张手边你最喜欢的一件小文具或桌面小物件',
    description: '日常中一直默默陪伴你的小帮手，给它一张特写吧。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '笔、便利贴、小尺子或可爱的便签夹。',
  },
  {
    id: 'dt_059',
    title: '晚安仪式：在睡前给对方发一句特定的睡前暗号',
    description: '今晚入睡前，让这句特别的小暗语成为好梦的守护咒。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '例如：月亮打烊啦，小熊来站岗。',
  },
  {
    id: 'dt_060',
    title: '假装陌生人：假装第一次在街角咖啡馆偶遇对方，开场白你怎么搭讪？',
    description: '重回初次相遇的青涩心动，你会用什么老套又好笑的方式走上前？',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「同学你好，请问这里的 Wi-Fi 密码是不是喜欢你？」',
  },
  {
    id: 'dt_061',
    title: '回忆我们一起淋过的一场雨，或者走过的那条长长的夜路',
    description: '雨水打湿了衣角，路灯把影子拉得很长很长，当时聊了什么？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '虽然有点狼狈，但心里却像有暖炉一样踏实。',
  },
  {
    id: 'dt_062',
    title: '25 分钟番茄钟冲刺',
    description: '专注处理今天拖延最久的一件正经事，一口气攻克它！',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '设立一个单项目标，全力冲刺 25 分钟。',
  },
  {
    id: 'dt_063',
    title: '灵魂拷问：如果可以选择任何一种动物做我们的小管家，你选什么？',
    description: '家务小能手大狂想，哪种小可爱最适合在小窝里给你们打工？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '勤劳的小浣熊、会飞的猫头鹰、还是温顺的大金毛？',
  },
  {
    id: 'dt_064',
    title: '拍拍脚下的地砖或台阶，记录今天的步伐',
    description: '一步步踏踏实实走过的路，都有心底对彼此的牵挂。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '路上的落叶地砖、商场的瓷砖或是走廊的木地板。',
  },
  {
    id: 'dt_065',
    title: '借用超能力：如果把你的一个好习惯借给对方一天，你选哪个？',
    description: '把自己身上最棒的能量，无私地借给对方体验一下。',
    task_type: 'interaction',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '早起不赖床、多喝水、还是情绪超稳定？',
  },
  {
    id: 'dt_066',
    title: '谐音梗大挑战：用对方的名字谐音编一个可爱的小谐音笑话',
    description: '发挥谐音梗扣钱的魔力，看看能不能把对方逗得又好气又好笑。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '开动脑筋，为 TA 量身定制专属谐音梗。',
  },
  {
    id: 'dt_067',
    title: '想想第一次去对方常去的地方时，那个下午或晚上的空气是什么味道？',
    description: '走进对方曾经独自生活的轨迹，那份好奇与探寻的心情。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那家常去的咖啡馆、那所学校的林荫道、或是小街景。',
  },
  {
    id: 'dt_068',
    title: '10 分钟深呼吸与放空',
    description: '闭上双眼，做 15 次深长缓慢的腹式呼吸，让大脑彻底休息。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '吸气 4 秒，屏气 2 秒，呼气 6 秒。',
  },
  {
    id: 'dt_069',
    title: '美食哲学：吃火锅第一口必须涮什么？看我们能不能达成共识',
    description: '火锅江湖的头道菜大辩论，是脆爽毛肚、嫩滑牛肉还是宽粉？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '说出你的火锅头牌，看看我们口味是不是天生一对。',
  },
  {
    id: 'dt_070',
    title: '拍一张光线透过窗户照进来的明暗光斑',
    description: '生活里总有细碎的光，落在桌角或地板上格外温柔。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '阳光洒在桌面、墙壁或窗帘上的光影。',
  },
  {
    id: 'dt_071',
    title: '随身锦囊：写一句给对方今天遇到烦恼时的「解压小咒语」',
    description: '当 TA 感到累或者沮丧时，默念这句咒语就能满血复活！',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「宇宙超级无敌大可爱，今天也辛苦啦！」',
  },
  {
    id: 'dt_072',
    title: '角色互换：假装你是对方，模仿 TA 耍赖或撒娇时的经典语气',
    description: '惟妙惟肖模仿对方平时的神态，让 TA 自己听听平时有多可爱。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '把 TA 最常说的口头禅和傲娇神态演出来！',
  },
  {
    id: 'dt_073',
    title: '聊聊我们看过的第一部电影，散场后灯光亮起时两个人说了什么？',
    description: '电影演了什么或许已经模糊，但当时并肩坐在一起的拘谨历历在目。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '哪部电影？当时谁先提议去看电影的？',
  },
  {
    id: 'dt_074',
    title: '15 分钟肩颈舒展',
    description: '跟着拉伸动作轻转脖子，向后扩胸，给紧绷了一天的肌肉减压。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '做一组温和的肩颈伸展。',
  },
  {
    id: 'dt_075',
    title: '理想周末：完全不设闹钟的一天，你最希望几点自然醒？',
    description: '摆脱打工人的时间枷锁，你身体最向往的生物钟节奏是怎样的？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '睡到上午十点、还是伴着晨光八点自然醒来伸个懒腰？',
  },
  {
    id: 'dt_076',
    title: '拍拍身边任何一件绿色的植物或叶子',
    description: '给眼睛做个深呼吸，也把一抹生机勃勃的绿意送给 TA。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '阳台的花草、办公桌的小多肉、或是路边的大树。',
  },
  {
    id: 'dt_077',
    title: '爱的便签：用一句话形容你今天有多想念 TA',
    description: '想念有时候是具象的，把你的心跳电波发过去吧。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「像等红灯变绿灯一样，每分每秒都在盼着见到你。」',
  },
  {
    id: 'dt_078',
    title: '奇怪特长：说出一个你平时完全用不上的搞笑无用小技能',
    description: '每个人身上都有一些奇奇怪怪但毫无实际用途的无用天赋，快招认！',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '卷舌头、耳朵会动、单挑眉毛或是能倒背圆周率？',
  },
  {
    id: 'dt_079',
    title: '回忆刚认识时对彼此的第一印象，和现在相比有什么最大的反差？',
    description: '从最初礼貌客套的陌生人，到如今毫无防备的小无赖，反差有多大？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '「刚认识时以为你挺高冷的，没想到其实是个搞笑女/男！」',
  },
  {
    id: 'dt_080',
    title: '20 分钟屏幕离线时光',
    description: '放下手机和电脑，望向窗外或闭目养神，找回没有通知打扰的清净。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '把手机倒扣在桌上，安静度过 20 分钟。',
  },
  {
    id: 'dt_081',
    title: '深度聊天：你最近一次感到被深深理解和包容，是什么时候？',
    description: '被看见、被接纳是爱最深刻的体现，聊聊那个让你心头一暖的时刻。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '是因为哪句话，或是哪个默契的举动让你放下了所有防备？',
  },
  {
    id: 'dt_082',
    title: '拍一张今天吃到的最满意的一口食物特写',
    description: '好好吃饭是最大的幸福，把舌尖上的满足打包分享。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '午餐的一道好菜、下班路上买的小吃或是甜点。',
  },
  {
    id: 'dt_083',
    title: '微笑挑战：发一句能让对方看到后立刻笑出来的搞怪悄悄话',
    description: '快乐是最好的润滑剂，看看能不能一秒戳中 TA 的笑穴。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '讲个无厘头谐音梗，或者一句可爱的歪理。',
  },
  {
    id: 'dt_084',
    title: '超市大作战：如果给你们 5 分钟在超市免费搬空货架，你最想抢什么？',
    description: '推着购物车百米冲刺，你会先直奔零食区还是直奔冰柜？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '车里一定要堆满大包薯片和冰淇淋！',
  },
  {
    id: 'dt_085',
    title: '那次让我们两个笑到在路上走不动路的经历，还记得是因为什么吗？',
    description: '哪怕在外人看来微不足道的小傻事，也能让两个人笑出眼泪来。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '记下那个哪怕想起来依然会忍不住嘴角上扬的瞬间。',
  },
  {
    id: 'dt_086',
    title: '15 分钟心流写写画画',
    description: '专心练字、涂鸦或写手账，不追求完美，只专注笔尖与纸面的触感。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '写下一段喜欢的摘抄，感受专注的心流。',
  },
  {
    id: 'dt_087',
    title: '未来想象：十年后的今天，你希望我们会在哪里吃早餐？',
    description: '十年光阴弹指过，描绘一下你心中那个充满烟火气的未来清晨。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '大阳台上的花草旁、异国小镇的木桌前、还是温馨的小厨房？',
  },
  {
    id: 'dt_088',
    title: '拍拍你的口袋或包包里掏出来的 3 样小物件',
    description: '看看平时你出门都会把哪些心爱的小物件随身带在身边。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '钥匙、耳机、润唇膏、小卡片等。',
  },
  {
    id: 'dt_089',
    title: '今日比心：在心里对对方默念三次「谢谢你陪在我身边」',
    description: '感恩相遇，因为有彼此的参与，生活才有了甜丝丝的底色。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '默念完毕后，给对方发一个爱心表情。',
  },
  {
    id: 'dt_090',
    title: '动物世界：如果你们俩变成两只小动物生活在森林里，会是什么动物？',
    description: '是一只小熊和一只小兔子，还是两只整天在树梢打闹的小松鼠？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊你们对应的动物形象和森林日常。',
  },
  {
    id: 'dt_091',
    title: '我们第一次闹别扭或者小争执之后，是怎么破冰和好的？',
    description: '爱不是没有摩擦，而是在摩擦之后依然愿意给对方一个台阶和拥抱。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '是谁先递过来一杯奶茶，还是谁先忍不住噗嗤一笑？',
  },
  {
    id: 'dt_092',
    title: '20 分钟晚间情绪沉淀',
    description: '回顾今天发生的事情，梳理杂乱思绪，写下一份轻松的随笔。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '整理今日心得，让心情归零。',
  },
  {
    id: 'dt_093',
    title: '生活琐事：你觉得我们两个人之间最像老夫老妻的瞬间是什么？',
    description: '褪去客套与拘谨，那些毫无掩饰的日常默契，最是深情。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '互相递纸巾不用说话、逛超市熟练地兵分两路拿菜…',
  },
  {
    id: 'dt_094',
    title: '拍下你现在正看着的电脑或书本的一角',
    description: '各自在自己的世界里努力，知道屏幕另一端有 TA 在陪伴。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '写满笔记的纸页、正在工作的屏幕一隅。',
  },
  {
    id: 'dt_095',
    title: '愿望存款：给你们的恋爱存折存入一个想共同实现的小心愿',
    description: '一点一滴记录下属于两个人的未来愿景，等待日后逐一兑现。',
    task_type: 'interaction',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '一起去坐摩天轮、一起学做提拉米苏…',
  },
  {
    id: 'dt_096',
    title: '口头禅大搜查：指出一个对方平时自己都没发觉的下意识口头禅',
    description: '相处久了，你常常比对方自己更清楚 TA 说话时爱带哪个语气词。',
    task_type: 'random',
    action_type: 'input',
    category: '观察',
    prompt_hint: '「就是说」「讲真」「嗷呜」「那个什么」…',
  },
  {
    id: 'dt_097',
    title: '对方曾经做过哪件让你超级感动、甚至眼眶微热的小举动？',
    description: '那些没有被大肆宣扬的默默付出，往往最深地烙印在记忆最深处。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '生病时的跨城探望、寒风里递过来的热烤红薯…',
  },
  {
    id: 'dt_098',
    title: '10 分钟眼部 SPA 休息',
    description: '放下手机眺望远方最远处的绿树或建筑物，搓热手心敷敷眼睛。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '让疲惫的双眼享受片刻温热与放松。',
  },
  {
    id: 'dt_099',
    title: '电影片名：如果把我们的故事拍成一部电影，片名会叫什么？',
    description: '是文艺舒缓的剧情片，还是充满欢声笑语的浪漫轻喜剧？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '取一个契合你们恋爱气质的浪漫片名。',
  },
  {
    id: 'dt_100',
    title: '拍拍今天路上偶遇的一只小猫、小狗或小鸟',
    description: '街角遇到的可爱小生命，常常是疲惫一天里最好的解药。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '晒太阳的小猫、散步的修狗或是停在树梢的鸟。',
  },
  {
    id: 'dt_101',
    title: '专属拥抱：隔空给对方送一个 10 秒钟的紧紧大拥抱',
    description: '张开双臂，想象彼此贴近的温度，把安心与依赖抱个满怀。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '心里数 10 下，把大大的拥抱发射过去！',
  },
  {
    id: 'dt_102',
    title: '奇怪童年梦想：聊聊你小时候做过最离谱、最天马行空的一个梦想',
    description: '谁小时候没做过几个荒诞不经的梦呢？说出来让对方乐呵一下。',
    task_type: 'random',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '想当小卖部老板天天吃辣条、想去太空抓外星人…',
  },
  {
    id: 'dt_103',
    title: '翻出一张我们都很喜欢的旧合照，温习当时按下快门那一秒的心情',
    description: '定格在像素里的笑容，永远不会随时间的流逝而褪色变淡。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '照片里两个人的表情、当时的背景与空气的温度。',
  },
  {
    id: 'dt_104',
    title: '20 分钟午后充电小憩',
    description: '定个闹钟安静闭目养神 20 分钟，给下午的大脑充满电量。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '趴在桌上午休，或是安静闭目。',
  },
  {
    id: 'dt_105',
    title: '童年秘密：你小时候最喜欢但别人觉得奇怪的一个小怪癖是什么？',
    description: '童年那些奇奇怪怪的小执念，今天毫无保留地坦白给对方听吧。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '喜欢收集落叶根、按固定路线走格子、喜欢闻刚印好的书本香…',
  },
  {
    id: 'dt_106',
    title: '拍拍今天天空中像某种动物或图形的云朵',
    description: '抬头看云，猜猜它像棉花糖、小羊还是一颗爱心？',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '天空中飘过的那朵独特的云。',
  },
  {
    id: 'dt_107',
    title: '交换好心情：今天你遇到的哪个瞬间让你感到被深深治愈？',
    description: '把生活里采集到的快乐光芒，转述给最心爱的人听。',
    task_type: 'interaction',
    action_type: 'input',
    category: '分享',
    prompt_hint: '路边小花绽放、吃到香甜的烤红薯、工作顺利搞定…',
  },
  {
    id: 'dt_108',
    title: '时间机器：如果能坐时间机器穿越到 50 年后看一眼，你想看什么？',
    description: '看一眼头发花白的老头老太太，是不是依然手拉手坐在公园长椅上？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '看看未来的科技，还是看看我们未来的小院子？',
  },
  {
    id: 'dt_109',
    title: '还记得第一次收到对方发来长篇文字信息时的感觉吗？',
    description: '手机屏幕上密密麻麻的真心话，每一个字都像在心上轻轻跳动。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那份认真的倾诉，当时读完一遍又忍不住重读了一遍。',
  },
  {
    id: 'dt_110',
    title: '15 分钟沉浸式听歌',
    description: '各自戴上耳机，专注听完一张轻音乐或经典专辑，不切歌不看手机。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '让音乐的旋律洗刷所有焦虑。',
  },
  {
    id: 'dt_111',
    title: '愿望清单：如果今年只能完成一个长途旅行的心愿，你想去哪里？',
    description: '世界很大，挑一个你最想拉着 TA 的手去印下足迹的目的地。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '去看雪山、去吹海风、还是去探索古老的小古镇？',
  },
  {
    id: 'dt_112',
    title: '拍一张今天身上穿搭的颜色搭配细节',
    description: '看看今天你们俩是不是又不约而同穿了相似色系呢？',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '衣服的袖口、毛衣纹理、或是袜子的可爱配色。',
  },
  {
    id: 'dt_113',
    title: '互换角色：如果今天由你当一天「大家长」，你会给 TA 安排什么？',
    description: '拥有绝对宠溺权，今天你说了算，要带 TA 怎么玩？',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '规定 TA 今天必须睡懒觉、必须吃一顿大餐…',
  },
  {
    id: 'dt_114',
    title: '灵魂画手：随手在草稿纸上涂鸦一个搞笑火柴人，代表对方此时的形象',
    description: '灵魂画技不需要基本功，抓取神韵，发给 TA 接受来自对方的制裁吧！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '画好拍一张照，或者用文字描述你的大作。',
  },
  {
    id: 'dt_115',
    title: '回忆一次我们一起吃到超级惊艳的美食，当时两个人说了什么？',
    description: '味蕾被同时点亮的奇妙瞬间，美食因为有彼此的分享才加倍美味。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那口惊艳的牛排、那碗热气腾腾的拉面、或是巷子里的烧烤。',
  },
  {
    id: 'dt_116',
    title: '25 分钟高效专注',
    description: '挑出手头最核心的一项待办，关掉聊天软件，全神贯注完成它。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '一口气写完总结、写好代码或整理好资料。',
  },
  {
    id: 'dt_117',
    title: '恋爱温度：你觉得什么时候的对方会让你觉得特别温柔？',
    description: '那个瞬间仿佛四周的背景音都静止了，只剩下对方眼里漾开的光。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '为你掖被角、说话带轻声笑意、或是摸摸你的头的时候。',
  },
  {
    id: 'dt_118',
    title: '拍下一张今天随手拿到的包装纸或小票据',
    description: '平凡生活里细小的时间印记，也藏着今天的小故事。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '咖啡杯套、小超市收银条、或是电影票根。',
  },
  {
    id: 'dt_119',
    title: '悄悄话：说一件你一直觉得对方做得很可爱但 TA 自己没察觉的举动',
    description: '情人眼里出西施，有些小动作在你的视线里别提多可爱了。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '专注时鼓起的腮帮子、吃到好吃的眼睛会放光…',
  },
  {
    id: 'dt_120',
    title: '假设大挑战：如果突然中了一千万大奖，第一件给对方买的东西是什么？',
    description: '暴富后的第一笔开销，往往藏着心底最想弥补或送给对方的愿望。',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '买下心心念念的大房子、还是带 TA 环游世界？',
  },
  {
    id: 'dt_121',
    title: '聊聊我们第一次坐在一起长谈，聊到深夜都不想睡觉的那次经历',
    description: '夜色渐浓，话题却像泉水一样涌出，第一次发现彼此灵魂如此契合。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那天晚上聊了什么人生梦想、童年过往或是情感心路？',
  },
  {
    id: 'dt_122',
    title: '10 分钟身体扫描放松',
    description: '从头顶、面部、双肩到脚尖，逐一部位用意念感受放松与沉静。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '平躺或端坐，释放每寸肌肉的紧张感。',
  },
  {
    id: 'dt_123',
    title: '幸福定义：用三个名词描述你心中最完美的「家」',
    description: '家不仅是钢筋水泥的居所，更是心安歇的归宿，它该由什么构成？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '灯光、猫咪、笑声、热汤、地毯…',
  },
  {
    id: 'dt_124',
    title: '拍拍身边带有温暖木质纹理的小角落',
    description: '木头的温润质感，让人一眼看过去心里就觉得很踏实。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '木桌、木门、小相框或木质收纳盒。',
  },
  {
    id: 'dt_125',
    title: '互相打气：对 TA 说一句「无论发生什么，我都坚定地站在你身后」',
    description: '最强大的后盾，往往来自于一句毫无保留的信赖与偏爱。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '给正在奋斗的 TA 吃下一颗最安心的定心丸。',
  },
  {
    id: 'dt_126',
    title: '终极二选一：夏天永远没有空调 vs 冬天永远没有暖气热水，你选哪个？',
    description: '残酷的人性与温度大抉择，看看你们是不是在同一个耐热/耐寒体质里。',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '给出你的选择，并说出你坚决不向另一个妥协的理由！',
  },
  {
    id: 'dt_127',
    title: '还记得对方最让你感到心疼的一个疲惫或难过的瞬间吗？',
    description: '看到 TA 耷拉下肩膀的那一刻，心里恨不得能替 TA 承担所有风雨。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '默默给对方递上纸巾，或者只是紧紧握住 TA 的双手。',
  },
  {
    id: 'dt_128',
    title: '15 分钟房间微整理',
    description: '收拾一下床铺、理顺衣物或给垃圾袋封口，给生活空间做个小微调。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '把身边的环境打理得干干净净。',
  },
  {
    id: 'dt_129',
    title: '灵感时刻：最近有什么书、电影或音乐深深触动了你的心？',
    description: '心灵被轻轻撞击的那一刻，把这份精神世界的共鸣也带给 TA。',
    task_type: 'question',
    action_type: 'input',
    category: '分享',
    prompt_hint: '聊聊那部作品最打动你的那个核心内核。',
  },
  {
    id: 'dt_130',
    title: '拍一张自己手部的影子轮廓',
    description: '在墙壁或桌面上比一个小手势，让影子代你向 TA 问好。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '阳光下拉长的小手影，比个剪刀手或小狐狸。',
  },
  {
    id: 'dt_131',
    title: '心动重现：今天挑一个瞬间，认真对 TA 说一句「我真的好喜欢你」',
    description: '喜欢是需要常常表达的，一句真诚的告白能抵御漫长风雨。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '不带任何修饰，直截了当地把心声说给 TA 听。',
  },
  {
    id: 'dt_132',
    title: '密电传送：用一串数字或字母暗号给对方发一条「神秘指令」',
    description: '设计专属于你们两个人的加密情报，看对方能不能顺利破译心意。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '例如利用九宫格拼音数字打出暗语。',
  },
  {
    id: 'dt_133',
    title: '翻出一首曾经在某个特定时期单曲循环的歌，一起重温一遍',
    description: '旋律是一台时间的时光机，只要前奏响起，就能瞬间带人回到过去。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那首歌叫什么名字？代表着你们哪一段特别的记忆？',
  },
  {
    id: 'dt_134',
    title: '20 分钟纯粹静默相伴',
    description: '在 BIBU！小窝里开启专注计时，相隔两地也知道彼此正在努力。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '共同进入专注界面，默默守候。',
  },
  {
    id: 'dt_135',
    title: '换位思考：你觉得在对方眼里，你最可爱的一个小缺点是什么？',
    description: '所谓情人眼里出西施，连有些小任性都会变成让人忍俊不禁的萌点。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '爱吃醋、选择困难症、或是偶尔像小树袋熊一样黏人？',
  },
  {
    id: 'dt_136',
    title: '拍拍门把手或玄关的一角，记录归家的瞬间',
    description: '推开门的那一刻，把一整天的疲惫都留在门外。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '玄关的地垫、钥匙盘或暖暖的门锁。',
  },
  {
    id: 'dt_137',
    title: '眼神接力：回忆对方看着你时最温柔的一次眼神',
    description: '眼睛是藏不住爱意的窗口，那个让你沦陷的注视还记得吗？',
    task_type: 'interaction',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '在黄昏的街头、或是灯光柔和的餐桌旁…',
  },
  {
    id: 'dt_138',
    title: '奇葩搭配：你吃过最让人一头雾水但意外觉得很好吃的黑暗料理是什么？',
    description: '美食世界的反叛分子，什么奇怪的搭配曾经惊艳过你的味蕾？',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '辣条配冰淇淋、西瓜蘸酱油、榴莲烤肉…',
  },
  {
    id: 'dt_139',
    title: '回忆一次我们一起等待日落、日出或者星空的经历',
    description: '大自然最壮丽的画布前，我们并肩伫立，天地辽阔，我们渺小却相依。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '海边的夕阳、山顶的微光、或是草地上数星星的夜晚。',
  },
  {
    id: 'dt_140',
    title: '15 分钟白噪音陪伴',
    description: '戴上耳机听一段雨声、森林鸟鸣或壁炉柴火声，在静谧中安顿身心。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '沉浸在治愈的环境音效中。',
  },
  {
    id: 'dt_141',
    title: '减压方式：心情特别烦闷的时候，什么样的方式最能让你迅速回血？',
    description: '每个人都有专属的解压阀，互相了解才能在对方累时送上最贴心的照顾。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '痛快洗个热水澡、大吃一顿甜品、痛快睡大觉还是散步？',
  },
  {
    id: 'dt_142',
    title: '拍一张你最喜欢的一个水杯特写',
    description: '天天捧在手心里的杯子，拍下来让对方眼熟一下。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '你最常用的大容量水壶或可爱的陶瓷杯。',
  },
  {
    id: 'dt_143',
    title: '减压小帮手：如果能帮对方分担今天的一件事，你想帮 TA 做什么？',
    description: '把对方肩膀上的重担分过来一半，爱就是彼此体谅。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '帮 TA 赶完今天的工、还是帮 TA 跑腿洗碗？',
  },
  {
    id: 'dt_144',
    title: '流落荒岛：如果流落荒岛只能带三件非生存必需品，你会带什么？',
    description: '生存之外的精神寄托，你会把有限的行李额度留给哪三样宝贝？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '吉他、一本日记本、对方的照片还是游戏机？',
  },
  {
    id: 'dt_145',
    title: '聊聊我们第一次一起去超市大采购，推车里都装了些什么？',
    description: '推着购物车穿梭在货架之间，第一次真切感受到了「搭伙过日子」的踏实烟火气。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '抢着放进去的膨化食品、认真挑选的洗发水和水果。',
  },
  {
    id: 'dt_146',
    title: '20 分钟专注输入',
    description: '认真阅读一篇有深度、有启发性的长篇文章，汲取新的思考养分。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '专心读完一篇人物专访或深度报道。',
  },
  {
    id: 'dt_147',
    title: '季节偏好：如果一年四季只能留下一个季节，你希望是哪一个？',
    description: '春生、夏长、秋收、冬藏，哪一个季节的气候最合你的心意？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '满目新绿的初春、热烈明朗的盛夏、金黄凉爽的深秋、银装素裹的暖冬？',
  },
  {
    id: 'dt_148',
    title: '拍拍今天在路边或花坛里看到的小野花',
    description: '不经意间盛开在路旁的小花，是大地写给行人的诗。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '不知名的小黄花、迎风摇曳的花瓣。',
  },
  {
    id: 'dt_149',
    title: '信任告白：说出对方身上最让你感到安心和踏实的一个特质',
    description: '因为有 TA 在，世界再吵闹也能找回内心的安稳。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '说到做到、情绪稳定、或是永远耐心地倾听。',
  },
  {
    id: 'dt_150',
    title: '魔法药水：如果有一种药水能让你一秒精通一项技艺，你选什么？',
    description: '不用辛苦练习就能直接满级，你想立刻拥有哪门神仙手艺？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '精通八国语言、成为钢琴大师、还是拥有顶级厨艺？',
  },
  {
    id: 'dt_151',
    title: '还记得彼此刚互加好友时的第一条问候语吗？',
    description: '那个客气而礼貌的开场白，谁能想到后来会变成彼此生命中最重要的人呢？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '翻到微信聊天记录的最顶端，看看最初那几句拘谨的问候。',
  },
  {
    id: 'dt_152',
    title: '10 分钟站立拉伸与活动',
    description: '离开椅子站起来活动腰部和双腿，做 20 个原地踮脚尖和转腰动作。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '舒展筋骨，促进血液循环。',
  },
  {
    id: 'dt_153',
    title: '奇妙同伴：如果去无人岛只能带三本书，你会选哪三本？',
    description: '经得起反复阅读与咀嚼的精神食粮，你会把行李箱留给谁？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '一本小说、一本哲学书、还是一本野外求生指南？',
  },
  {
    id: 'dt_154',
    title: '拍拍今天工作或学习空间里最舒服的一隅',
    description: '整理得井井有条的一角，能给人带来一整天的好心态。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '点着香薰的角落、摆着小闹钟的书桌。',
  },
  {
    id: 'dt_155',
    title: '早餐建议：给对方明天的早餐搭配提一个营养又好吃的建议',
    description: '关心从第一餐开始，给对方规划一份元气满满的早点。',
    task_type: 'interaction',
    action_type: 'input',
    category: '分享',
    prompt_hint: '热豆浆配包子、牛奶燕麦配煎蛋…',
  },
  {
    id: 'dt_156',
    title: '互换身份一天：如果明天你变成了对方，你第一件事会去干嘛？',
    description: '顶着对方的身体度过一天，你会借机做点什么好玩的事情？',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '照照镜子看看对方视角里的自己、或是替 TA 吃顿大餐！',
  },
  {
    id: 'dt_157',
    title: '回忆我们一起度过的第一个彼此的生日，那天有什么难忘的细节？',
    description: '为了给对方制造一个小惊喜，偷偷策划、反复准备的那份诚挚用心。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '蛋糕上的蜡烛、亲手写的贺卡、或是许愿时注视着对方的目光。',
  },
  {
    id: 'dt_158',
    title: '15 分钟睡前情绪冥想',
    description: '回顾今天值得心存感激的三件小事，带着温柔与满足的心情准备入眠。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '在心里温习今天感受到的善意。',
  },
  {
    id: 'dt_159',
    title: '惊喜时刻：你更喜欢突如其来的偶遇小惊喜，还是精心策划的仪式感？',
    description: '了解彼此对待浪漫的期待方式，才能把心意送到对方心坎里。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '路过买的一枝向日葵，还是纪念日精心准备的烛光晚餐？',
  },
  {
    id: 'dt_160',
    title: '拍下今天天黑后窗外的城市夜光或路灯',
    description: '夜幕降临，万家灯火里，也有我们在彼此心里点亮的灯。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '暖黄色的路灯、车水马龙或是远处的霓虹。',
  },
  {
    id: 'dt_161',
    title: '默契击掌：隔空做一个击掌动作，为彼此今天所做的努力喝彩',
    description: '在各自的战场上拼搏了一整天，你们都是值得骄傲的冠军。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '「啪！」隔空拍一下手，今天辛苦啦！',
  },
  {
    id: 'dt_162',
    title: '外号大升级：根据对方今天的穿搭或发型，现编一个 6 字搞笑头衔',
    description: '头衔一定要气派又浮夸，念出来就能让人笑倒在沙发上。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「宇宙无敌瞌睡王」「脆皮毛绒小年糕」…',
  },
  {
    id: 'dt_163',
    title: '想想哪一次两个人一起赶车、赶路，虽然狼狈但现在想来超级好笑？',
    description: '狂奔在火车站的大厅里、拖着箱子在雨里冲刺，慌慌张张却一路紧握着手。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '气喘吁吁相视大笑的那一刻，狼狈也变成了勋章。',
  },
  {
    id: 'dt_164',
    title: '25 分钟断舍离时刻',
    description: '清理手机相册里的重复截图、无用视频和缓存，给手机和心灵都减负。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '删掉无用的陈旧文件，空间更充裕。',
  },
  {
    id: 'dt_165',
    title: '睡前畅想：如果今晚能做一个完全由你编剧的梦，你想梦见什么？',
    description: '在梦境的造梦剧场里，你打算给自己和对方安排什么奇妙大戏？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '去太空翱翔、潜入深海看发光的鲸鱼、还是重回学生时代？',
  },
  {
    id: 'dt_166',
    title: '拍拍你今天吃的水果或小零食',
    description: '香甜的水果和可口的零食，是给辛苦一天的自己的小小奖励。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '一颗切好的苹果、一把坚果或一颗草莓。',
  },
  {
    id: 'dt_167',
    title: '晚霞请假条：如果能批准对方今晚「提前下班/放松」，你想怎么陪 TA？',
    description: '假装给对方批一张假条，今晚的所有烦恼都暂且退下！',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '带 TA 去吃夜宵、看一部无脑搞笑喜剧…',
  },
  {
    id: 'dt_168',
    title: '反向撒娇：用最霸道、凶巴巴的语气跟对方说一句甜言蜜语',
    description: '外表冷酷内心柔软，把傲娇的精髓演绎到淋漓尽致！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「听好了，你今天必须给我开心，不然我就去抱你！」',
  },
  {
    id: 'dt_169',
    title: '对方身上哪一个习惯是认识之后慢慢被你传染或者互相影响的？',
    description: '两个人的生活方式在岁月里悄悄交融，活成了彼此身上的一部分。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '说话的语气词、喜欢喝的饮料口味、或是叠衣服的习惯。',
  },
  {
    id: 'dt_170',
    title: '20 分钟手部与手腕护理',
    description: '经常打字玩手机手腕容易酸，做一组手腕绕环与手指舒展操。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '转动双腕，双手交扣向外推伸。',
  },
  {
    id: 'dt_171',
    title: '恋爱感悟：两个人朝夕相处，你觉得最重要的第一原则是什么？',
    description: '支撑一段长久健康关系的基石，在你心中最坚固的那块砖是什么？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '坦诚沟通、彼此尊重、不翻旧账、还是保持独立空间？',
  },
  {
    id: 'dt_172',
    title: '拍一张书页上你今天读到最喜欢的一句话',
    description: '好的文字就像一盏灯，照亮心底某个柔软的角落。',
    task_type: 'photo',
    action_type: 'photo',
    category: '分享',
    prompt_hint: '书本上的铅笔划线，或者手机备忘录里的一句话。',
  },
  {
    id: 'dt_173',
    title: '听你倾诉：认真问问对方今天有没有遇到委屈，当 TA 的专属树洞',
    description: '把耳朵借给对方，不讲大道理，只负责全心全意陪伴与拥抱。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「今天过得开心吗？有什么想跟我吐槽的吗？」',
  },
  {
    id: 'dt_174',
    title: '听歌辨曲：打出一段你哼唱的拟声词文字，让对方猜是哪首歌',
    description: '用文字还原旋律的节奏感，看看两颗心的电波能不能对得上！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「登登登登~ 登登~ 登登登~」是哪首经典名曲？',
  },
  {
    id: 'dt_175',
    title: '回忆我们第一次一起做饭或烘焙的过程，成功了还是翻车了？',
    description: '厨房里手忙脚乱的烟火气，即使最后做成了黑暗料理也是最甜的一餐。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '谁负责切菜谁负责下锅？最后吃完是谁洗的碗？',
  },
  {
    id: 'dt_176',
    title: '10 分钟无负担发呆特权',
    description: '什么都不想，允许自己的大脑彻底关机 10 分钟，放空是充电的开始。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '坐在窗边看云发呆，享受无所事事的自在。',
  },
  {
    id: 'dt_177',
    title: '味道记忆：闻到什么味道会让你一瞬间联想到童年或故乡？',
    description: '气味是连接记忆深处最隐秘的通道，瞬间唤醒当年的空气与阳光。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '刚割完青草的清香、夏天暴雨初落泥土的腥香、妈妈熬汤的香气…',
  },
  {
    id: 'dt_178',
    title: '拍拍你的耳机或正在播放音乐的界面',
    description: '此时此刻流淌在你耳朵里的音符，也想让 TA 听听。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '耳机盒、正在旋转的音乐唱片界面。',
  },
  {
    id: 'dt_179',
    title: '互赠歌词：抄录一句最贴合你们当下状态的歌词发给 TA',
    description: '有时候旋律和歌词，最能精准说出心底那些羞于启齿的情话。',
    task_type: 'interaction',
    action_type: 'input',
    category: '分享',
    prompt_hint: '写下一句深情的歌词，配上歌名。',
  },
  {
    id: 'dt_180',
    title: '奇妙战队：如果要组一个双人超级英雄同盟，队名和口号要叫什么？',
    description: '两个拯救世界的小可爱，出场必须自带最酷炫拉风的开场白！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '设计你们的专属英雄称号与合体大招名称。',
  },
  {
    id: 'dt_181',
    title: '还记得那次一起去过的海边、公园或小山坡吗？风吹过来是什么感觉？',
    description: '大自然的微风吹动发丝，那是两个人世界里最纯粹舒展的一个午后。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '光着脚踩在沙滩上、或是坐在草地上看来往的放风筝的人。',
  },
  {
    id: 'dt_182',
    title: '20 分钟安静速读',
    description: '沉下心来连续阅读 10 页纸质书籍，在字里行间遇到另一个世界。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '泡一杯茶，伴着书香阅读。',
  },
  {
    id: 'dt_183',
    title: '习惯探秘：你身上有一个什么样的个人生活习惯是几乎没人知道的？',
    description: '私密空间里最真实随性的小日常，今天把这个小彩蛋揭晓给对方。',
    task_type: 'question',
    action_type: 'input',
    category: '分享',
    prompt_hint: '睡觉必须抱玩偶、吃薯片喜欢按大小排队…',
  },
  {
    id: 'dt_184',
    title: '拍一张手边任何红色或橙色的温暖物件',
    description: '暖色调的小物件，在视线里总能带来热气腾腾的温度。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '橘子、红色的笔、暖橙色的笔记本。',
  },
  {
    id: 'dt_185',
    title: '今日限定夸奖：从头到脚挑一个部位，狠狠夸夸 TA',
    description: '无论头发丝、眼睛、声音还是穿搭，TA 浑身都是闪光点。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「今天的声音听起来特别温柔治愈！」',
  },
  {
    id: 'dt_186',
    title: '穿越古代：如果穿越回古代，你觉得我们俩谁像大侠，谁像狗头军师？',
    description: '仗剑走天涯的江湖情侣，一个负责武力输出，一个负责出谋划策！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊你们在古代客栈里行侠仗义的江湖画面。',
  },
  {
    id: 'dt_187',
    title: '回忆某一个夏夜或冬夜，我们两个人戴着同一副耳机听歌的时刻',
    description: '一人一只耳机，线缆在两张脸之间轻轻晃动，心跳跟着同一段节拍律动。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '左声道是你，右声道是我，音乐把空气染成了金色。',
  },
  {
    id: 'dt_188',
    title: '15 分钟温水品茗',
    description: '泡一杯温暖的花草茶或热白开，细细品味入口的温度与清香。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '小口慢饮，感受水温流淌过心口。',
  },
  {
    id: 'dt_189',
    title: '梦想家园：你更喜欢窗外能看到大海的房子，还是能看到群山的木屋？',
    description: '波澜壮阔的蓝色浪潮，与郁郁葱葱的静谧山林，你向往哪种风景？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊坐在窗边看海/看山的悠闲下午生活。',
  },
  {
    id: 'dt_190',
    title: '拍拍今天出门或回家路过的那座天桥或路口',
    description: '每天走过的街景，因为心里想着一个人而变得格外生动。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '熟悉的转角、等红绿灯的斑马线。',
  },
  {
    id: 'dt_191',
    title: '给未来的信：给一年后的你们俩写下一句简短的期许',
    description: '把愿望装进时间的漂流瓶，一年后再回来看一定超级奇妙。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '希望一年后的我们依然热烈相爱，去看了想看的风景。',
  },
  {
    id: 'dt_192',
    title: '电影片名：给今天经历的一整天事情，取一个好莱坞大片般的浮夸片名',
    description: '平凡的日常经过夸张修辞，也能变成惊心动魄的冒险传奇！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '《打工人逆风翻盘记》《被窝保卫战：终极对决》…',
  },
  {
    id: 'dt_193',
    title: '聊聊对方曾经送给你的一样最特别、最出人意料的礼物',
    description: '不是昂贵的奢侈品，而是那个精准击中你喜好的奇思妙想小物件。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那件礼物是什么？当时收到时你脸上的表情是怎么样的？',
  },
  {
    id: 'dt_194',
    title: '25 分钟深度思考备忘',
    description: '就近期正在思考的一个选择或小计划，在纸上梳理出利弊与思路。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '理清思路，让下一步行动更笃定。',
  },
  {
    id: 'dt_195',
    title: '沟通偏好：闹矛盾的时候，你更需要立刻当面说清楚，还是先安静冷静一下？',
    description: '摸清彼此的脾气与缓冲时间，是化解一切争吵最关键的密钥。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '告诉对方你最舒服的复盘和解节奏。',
  },
  {
    id: 'dt_196',
    title: '拍一张你今天随手写下的一行字或小草稿',
    description: '手写的字迹总带着屏幕打字没有的温度与呼吸感。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '便签条上的随笔、待办清单或是随手画的小人。',
  },
  {
    id: 'dt_197',
    title: '晚间问候：在今晚整点准时给对方发一条温馨的问候',
    description: '守候在时间节点上的微小仪式感，让 TA 知道有人一直在意。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '整点发出一句「今晚也要开心呀」。',
  },
  {
    id: 'dt_198',
    title: '奇妙发明：如果能发明一样专门解决情侣烦恼的神奇道具，那会是什么？',
    description: '脑洞大开的未来科技，专门服务于两个人甜甜的日常互动！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '隔空传送拥抱机、情绪精准翻译手环、防生气喷雾…',
  },
  {
    id: 'dt_199',
    title: '回忆刚确认关系的那天晚上，你回到家后一个人偷偷做了什么？',
    description: '兴奋得在床上打滚、反复看着手机傻笑、还是迫不及待跟闺蜜/兄弟报喜？',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '心头那只终于落地的快乐小鹿，那天晚上失眠到几点？',
  },
  {
    id: 'dt_200',
    title: '10 分钟体态重置',
    description: '靠墙端正站立 5 分钟，后脑勺、双肩、脚跟贴墙，唤醒挺拔体态。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '调整呼吸，找回挺拔端正的身姿。',
  },
  {
    id: 'dt_201',
    title: '温暖时刻：对方做过的哪件事，让你觉得自己是被无条件偏爱着的？',
    description: '那种全世界在下沉而 TA 只看着你的笃定，最让人安心踏实。',
    task_type: 'question',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '所有好吃的都留给你第一口、任何时候都把你的感受放首位…',
  },
  {
    id: 'dt_202',
    title: '拍拍身边任何一件毛茸茸或柔软的东西',
    description: '摸起来软乎乎的东西最治愈，把这份软糯也传递过去。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '毛毯、抱枕、毛绒小玩具或是围巾。',
  },
  {
    id: 'dt_203',
    title: '温暖承诺：许诺一个近期一定会为对方实现的小动作',
    description: '言出必行的小确幸，会让平凡的日常变得格外值得期待。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '下次见面给你带你爱喝的那家奶茶！',
  },
  {
    id: 'dt_204',
    title: '逆向思维：想出一个听起来像在互怼但其实超级宠溺的称呼',
    description: '互损才是情侣日常的最高境界，明贬暗褒的小情趣格外上头。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「难伺候的小祖宗」「家养爱哭包」…',
  },
  {
    id: 'dt_205',
    title: '想想我们第一次跟彼此的朋友或家人提起对方时的情景',
    description: '带着一份骄傲又有一丝羞涩的心情，把那个藏在心尖上的人介绍给世界。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '当时你是怎么描述 TA 的？他们听了之后给出了什么有趣的评价？',
  },
  {
    id: 'dt_206',
    title: '20 分钟本周个人小复盘',
    description: '回想这周有什么做得好的地方，给努力生活的自己好好点个赞。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '总结收获，发现自己的闪光进步。',
  },
  {
    id: 'dt_207',
    title: '爱好分享：如果有一整天空闲时间完全没人打扰，你最想沉迷在什么事里？',
    description: '留给自己的一方自留地，用来安放平日里被挤压的小爱好。',
    task_type: 'question',
    action_type: 'input',
    category: '分享',
    prompt_hint: '拼一天乐高、通关一款单机游戏、烘焙、或是拼布手作？',
  },
  {
    id: 'dt_208',
    title: '拍一张低头看地面的视角照',
    description: '记录你正站立着的此时此地，世界很大，我们在同一个时空。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '站立的地面、脚尖前的一片小树叶。',
  },
  {
    id: 'dt_209',
    title: '情绪雷达：猜猜对方此刻的电量条还剩百分之几？',
    description: '心有灵犀大检验，看看你能不能精准捕捉到 TA 现在的疲惫或兴奋。',
    task_type: 'interaction',
    action_type: 'input',
    category: '猜测',
    prompt_hint: '「我猜你现在电量只剩 15% 了，急需抱抱充电！」',
  },
  {
    id: 'dt_210',
    title: '脑洞心情灯：如果人的头顶会根据情绪显示红绿灯，你此刻亮什么灯？',
    description: '把抽象的心情具象成发光的信号，看看对方能不能读懂你的频率。',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '绿灯代表心情大好，黄灯代表需要充电，粉灯代表想你了！',
  },
  {
    id: 'dt_211',
    title: '回忆一次我们俩一起经历过的极端天气（大暴雨、大雪或大风天）',
    description: '窗外狂风暴雨呼啸，屋里两个人围坐在一起，那种安全感格外浓烈。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '窗户玻璃上的雨痕，热气腾腾的泡面或是暖炉的微光。',
  },
  {
    id: 'dt_212',
    title: '15 分钟静心手工折纸',
    description: '随手找张纸叠一只纸鹤或纸飞机，在翅膀上写下一个送给 TA 的小愿望。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '动动手指，体验手工制作的小乐趣。',
  },
  {
    id: 'dt_213',
    title: '世界暂停：如果所有人静止 24 小时只有我们能动，你想拉着 TA 干嘛？',
    description: '空无一人的城市街道变成了你们俩的游乐场，第一站去哪儿探险？',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '逛遍平时人挤人的游乐园、去博物馆近距离观察恐龙骨架…',
  },
  {
    id: 'dt_214',
    title: '拍拍身边的时钟或屏幕上的时间',
    description: '滴答走过的时间，每一秒都在悄悄累积我们在一起的历程。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '挂钟的指针、手表的表盘或数字时钟。',
  },
  {
    id: 'dt_215',
    title: '交换歌单：让对方选一首歌，你今天找时间安静听完',
    description: '走进对方的音乐世界，去感受 TA 耳机里正在流淌的情绪。',
    task_type: 'interaction',
    action_type: 'input',
    category: '分享',
    prompt_hint: '听完后告诉 TA 你最喜欢哪句旋律。',
  },
  {
    id: 'dt_216',
    title: '测谎大作战：说三句关于你今天的事情（两真一假），让对方猜哪个是假的',
    description: '考验眼力与直觉的推理时刻，看看谁才是明察秋毫的小侦探！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '列出三件事，等对方揭晓猜测后再公布答案。',
  },
  {
    id: 'dt_217',
    title: '聊聊我们在旅途中发生过的一件搞笑小插曲',
    description: '迷路了走进一条死胡同、买错了车票、或是被奇怪的当地小吃酸得龇牙咧嘴。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '不在计划里的意外插曲，往往成了旅行中最鲜活难忘的回忆。',
  },
  {
    id: 'dt_218',
    title: '20 分钟理清明日清单',
    description: '把明天最重要的 3 件待办写在显眼处，让明天从容不迫地开始。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '清晰规划日程，今晚睡得更踏实。',
  },
  {
    id: 'dt_219',
    title: '理想晚餐：你心中最治愈的一顿晚饭，餐桌上应该摆着哪些菜品？',
    description: '热腾腾的饭菜香气最抚凡人心，描述一下你心中满分的私房菜单。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '番茄牛腩煲、清炒时蔬、一碗温热的靓汤…',
  },
  {
    id: 'dt_220',
    title: '拍一张冰箱里或者零食柜里的一角',
    description: '塞得满满的小空间，装载着生活里实实在在的烟火气。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '整齐码放的饮料罐、或是零食收纳篮。',
  },
  {
    id: 'dt_221',
    title: '互相监督：提醒对方放下耸起的肩膀，活动下脖子，喝一口水',
    description: '日常里细水长流的关心，比什么都来得更加切实与贴心。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '放下肩膀，深吸一口气，把水杯端起来吧！',
  },
  {
    id: 'dt_222',
    title: '专属情侣货币：如果恋爱里有一种专用货币，用什么当等价物最合适？',
    description: '在这个浪漫的微型经济体系里，什么能买到对方最珍贵的特权？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '一个亲亲值 10 块钱，一次按摩值 50 块钱？',
  },
  {
    id: 'dt_223',
    title: '还记得对方第一次做让你觉得「天哪，TA 也太帅/太美了吧」的瞬间吗？',
    description: '自带聚光灯的那一秒定格，整个人在视线里仿佛被镀上了一层金边。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '随手整理头发的侧颜、认真解答难题时的专注眼神…',
  },
  {
    id: 'dt_224',
    title: '10 分钟微风感知',
    description: '如果条件允许，走到窗边或阳台，静静感受 5 分钟掠过脸庞的自然微风。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '闭上眼，感受微风的温度与抚摸。',
  },
  {
    id: 'dt_225',
    title: '心灵避风港：当你感到外界压力山大时，心里最先想到的画面是什么？',
    description: '那个能瞬间抚平你焦虑情绪的精神锚点，藏着你心底最安全的防线。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '小窝里柔软的沙发、对方温暖的掌心、或是家乡的小院。',
  },
  {
    id: 'dt_226',
    title: '拍拍你今天戴的眼镜、手表或小手链',
    description: '日常贴身佩戴的小配件，见证着你一整天的点点滴滴。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '手腕上的表带、小发卡或是戒指。',
  },
  {
    id: 'dt_227',
    title: '浪漫暗号：约定一个今天只要发出来就代表「想抱抱」的特殊符号',
    description: '两个人之间的秘密协议，发出来就是无声的撒娇与呼唤。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '比如发一个小树袋熊表情，或者一个句号。',
  },
  {
    id: 'dt_228',
    title: '随机联想：听到「落叶」或「积雪」这个词，脑海里跳出的第一幅画面是什么？',
    description: '词语唤醒的潜意识记忆，往往连着心底最柔软的那份温情。',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊那个瞬间在你眼前浮现出的光影与气息。',
  },
  {
    id: 'dt_229',
    title: '回忆一次我们俩意见不同，但最后互相包容、各退一步的温暖体验',
    description: '在亲密关系里学会理解与退让，是我们共同成长的宝贵勋章。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '虽然有了分歧，但爱让彼此都愿意先伸出言和的手。',
  },
  {
    id: 'dt_230',
    title: '25 分钟背词或记忆冲刺',
    description: '集中注意力背 20 个外语单词或熟记一组知识点，体验记忆的充实。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '专心攻克一个小知识模块。',
  },
  {
    id: 'dt_231',
    title: '价值观小测：健康、财富、自由、陪伴，按重要性从高到低怎么排？',
    description: '审视内心最底层的价值排序，聊聊你为什么把某一项放在第一位。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '给出你的排序，听听对方的看法，求同存异。',
  },
  {
    id: 'dt_232',
    title: '拍下一片阳光下微尘飞舞的光柱或明暗交界线',
    description: '生活里的光影美学，往往藏在这些微小不经意的瞬间。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '午后斜射进室内的阳光切角。',
  },
  {
    id: 'dt_233',
    title: '心声速递：用「有你真好」为结尾造一个完整的句子送给对方',
    description: '生活琐碎有时让人疲惫，但只要想到有你，世界就变甜了。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「今天虽然遇到了小挫折，但想到晚上能跟你聊天，有你真好。」',
  },
  {
    id: 'dt_234',
    title: '搞笑禁令：在接下来的一小时聊天中不能出现「你」字，破戒发丑照！',
    description: '说话必须变着法子拐弯抹角，看看谁的语言组织能力更胜一筹。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '用「某人」「对方玩家」替代，谁先犯规谁认输！',
  },
  {
    id: 'dt_235',
    title: '想想曾经哪一次分别时，你一步三回头、舍不得离开的心情',
    description: '在站台、在校门口、在楼梯口，松开的手一次次又忍不住重新拉住。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '车子开动那一刻，隔着车窗挥手的倒影，心里写满了眷恋。',
  },
  {
    id: 'dt_236',
    title: '15 分钟身心减负划线法',
    description: '在草稿纸上写下此刻脑海里所有焦虑杂念，然后一笔一笔全部用力划掉！',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '把杂念具象化并亲手消除它。',
  },
  {
    id: 'dt_237',
    title: '浪漫主义：抛开商业包装，你觉得世界上最真正浪漫的事情是什么？',
    description: '不落俗套的浪漫，是在漫长岁月里依然对彼此保持好奇与温柔。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '老了还能牵手散步、记得对方随口说的一个小愿望并实现它…',
  },
  {
    id: 'dt_238',
    title: '拍拍今天走过的林荫路或人行横道',
    description: '绿树成荫的街道，是城市里最让人想散步的地方。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '阳光透过树叶洒在路上的斑驳树影。',
  },
  {
    id: 'dt_239',
    title: '专属电台：给对方点播一段你今天心里最想对 TA 说的独白',
    description: '化身电台主播，把今天心头掠过的那份温柔缓缓道来。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '录一段语音，或发一段长长的文字私信。',
  },
  {
    id: 'dt_240',
    title: '交换童年秘密：说出一件你以前从来没跟别人提起过的童年小糗事',
    description: '童年时期做过的那些傻乎乎的荒唐事，今天全盘托出吧！',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '偷偷把作业本藏在沙发底、假装生病逃避体育课…',
  },
  {
    id: 'dt_241',
    title: '回忆那件我们一起计划了很久、最终圆满实现的小心愿',
    description: '从最初纸上的勾勾画画，到最终身临其境的那一刻，成就有多巨大！',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那次蓄谋已久的旅行、那场期待已久的演唱会、或是共同置办的小家电。',
  },
  {
    id: 'dt_242',
    title: '20 分钟睡前断网准备',
    description: '提前把手机充上电放在伸手够不着的地方，关灯准备安稳入睡。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '远离蓝光干扰，进入宁静睡眠模式。',
  },
  {
    id: 'dt_243',
    title: '陪伴感：在对方做哪些细小举动的时候，会让你觉得特别心安？',
    description: '安全感往往不是大动干戈的誓言，而是日常里下意识的小细节。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '睡梦中把你往怀里揽一下、过马路自然牵起你的手…',
  },
  {
    id: 'dt_244',
    title: '拍一张带水珠的水杯或窗玻璃',
    description: '晶莹剔透的水珠，像是一颗颗落在生活里的小露珠。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '冷饮杯壁凝结的水雾、或是雨后窗户上的水珠。',
  },
  {
    id: 'dt_245',
    title: '恋爱小细节：告诉对方哪一次 TA 的小举动让你觉得「被深爱着」',
    description: '被坚定选择的感觉最动人，唤醒那些让人心头一颤的细节。',
    task_type: 'interaction',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '过马路时下意识把你拉到内侧、记得你的所有忌口…',
  },
  {
    id: 'dt_246',
    title: '超能力偷窥：如果今天能读懂对方内心真实想法 10 分钟，你想探查什么？',
    description: '给你一次读心神技，你最想悄悄潜入 TA 心底哪个神秘小房间？',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '看看 TA 此刻在偷偷想什么、或是最想吃什么。',
  },
  {
    id: 'dt_247',
    title: '翻翻以前的便签或备忘录，找到一条曾经随手记录关于对方的小文字',
    description: '当时的心动被白纸黑字诚实地保留了下来，如今读来依然鲜活滚烫。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '念出那条几百天前写下的碎碎念，温习当年的柔软心事。',
  },
  {
    id: 'dt_248',
    title: '10 分钟猫牛式脊柱拉伸',
    description: '在瑜伽垫或床上做简单的猫牛式呼吸延展，柔和活动每一节脊椎。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '吸气抬头塌腰，呼气低头弓背。',
  },
  {
    id: 'dt_249',
    title: '成长反思：在一起这一年多来，你觉得自己在哪个方面发生了积极改变？',
    description: '好的恋爱会让彼此都变成更宽阔、更自信、更温和的人。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '脾气变得更柔和、学会了表达爱意、变得更懂得体贴他人…',
  },
  {
    id: 'dt_250',
    title: '拍拍手边一件蓝色或青色的小物件',
    description: '像天空一样让人沉静的颜色，给今天带来一丝清凉与舒心。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '蓝色的书皮、青色的文件夹或水杯。',
  },
  {
    id: 'dt_251',
    title: '趣味誓言：编一个一本正经但内容超宠溺的情侣小誓言',
    description: '用严肃认真的法庭/契约口吻，写下最无厘头的宠爱条款。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「本人承诺：绝不抢对方碗里最后一片肉！」',
  },
  {
    id: 'dt_252',
    title: '脑回路测试：刚出炉脆脆的披萨边 vs 刚出锅油滋滋的炸鸡皮，你选哪个？',
    description: '吃货宇宙里的灵魂对决，看看你们在美食偏好上是同盟还是互补！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '做出你的选择，誓死守护你的终极美味信仰！',
  },
  {
    id: 'dt_253',
    title: '回忆第一次在对方面前彻底卸下防备、哭得稀里哗啦的时刻',
    description: '不再勉强自己扮演坚强的大人，把所有的脆弱与伤口放心地交由 TA 抚平。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那个温暖无声的拥抱，拍打后背的轻柔节奏，让你知道自己被全盘接纳。',
  },
  {
    id: 'dt_254',
    title: '15 分钟音符漫游',
    description: '闭上眼睛，专注于乐曲里每一声钢琴键的敲击或吉他弦的拨动。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '把注意力完全放在声音的起伏上。',
  },
  {
    id: 'dt_255',
    title: '礼物哲学：你更看重礼物的实用价值，还是它所包含的心意与惊喜度？',
    description: '摸清对方的心头好，日后挑礼物就能百发百中，绝不踩雷！',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊你收到过最满意的一份礼物是因为什么打动了你。',
  },
  {
    id: 'dt_256',
    title: '拍一张你今天坐的椅子或靠垫',
    description: '承托着你忙碌身躯的地方，今天它也辛苦啦。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '软软的办公椅、沙发一角或是靠枕。',
  },
  {
    id: 'dt_257',
    title: '情绪垃圾桶：邀请对方把今天积攒的所有不开心都倒在你这里',
    description: '不开心的事情说出来就减半，你的怀抱是 TA 永远的避风港。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「把所有郁闷都说给我听吧，听完我就把它们全都丢掉！」',
  },
  {
    id: 'dt_258',
    title: '特工指令：给对方发一条「紧急特工密令」，限时 5 分钟内执行完毕！',
    description: '假装自己是总部联络官，给外勤特工 TA 下达一条温暖的强制任务。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「代号 007，命你立刻在 5 分钟内喝光杯中温水！」',
  },
  {
    id: 'dt_259',
    title: '还记得我们一起走过的最长的一段路吗？那天你们聊了些什么？',
    description: '脚底走到发酸，天色从黄昏走到深黑，但只要身边是 TA，路再长也嫌短。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '在空旷的大街上压马路，把那些漫无边际的理想与心事统统聊了个遍。',
  },
  {
    id: 'dt_260',
    title: '25 分钟收件箱与消息清零',
    description: '回复完今天所有必须要处理的要紧消息，给今天一个干净利落的收尾。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '清空未读角标，告别拖延。',
  },
  {
    id: 'dt_261',
    title: '超能力借调：如果能从对方身上借走一项优秀特质给自己，你想借什么？',
    description: '欣赏对方身上自己不曾拥有的长处，这也是吸引彼此的磁场所在。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '条理清晰的逻辑思维、超高的情商沟通、强大的抗挫折能力…',
  },
  {
    id: 'dt_262',
    title: '拍拍今天随手买的小面包或烘焙点心',
    description: '刚出炉的小面包散发着麦香，看着就让人食指大动。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '可颂、吐司或可爱的小蛋糕。',
  },
  {
    id: 'dt_263',
    title: '清空烦恼：跟对方说一句「烦恼都丢给我，好运都留给你」',
    description: '最霸道又最温柔的护短，让 TA 知道自己永远被无条件罩着。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '拍拍胸脯，把好运气一股脑全转赠给 TA。',
  },
  {
    id: 'dt_264',
    title: '情绪拟声词：用一个拟声词（如咕噜咕噜、呼啦啦）形容你当下的状态',
    description: '不用复杂词汇，只用声音的形态还原你此刻的内心动态。',
    task_type: 'random',
    action_type: 'input',
    category: '表达',
    prompt_hint: '呼哧呼哧（忙碌中）、飘飘乎乎（好困想睡）…',
  },
  {
    id: 'dt_265',
    title: '回忆某一个普通的周末午后，两个人无所事事却觉得无比惬意的时光',
    description: '不用赶场，不用做任何宏大计划，就只是窝在一起发呆看书打盹。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '阳光慢慢移动到地板另一端，这就是生活最完美的安宁模样。',
  },
  {
    id: 'dt_266',
    title: '20 分钟并肩默契学习',
    description: '打开计时器，各自沉入书本或专业领域的钻研中，共同进步。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '两个人一起向上走，是最好的恋爱状态。',
  },
  {
    id: 'dt_267',
    title: '记忆胶囊：如果只能保留一段关于对方的记忆直到 80 岁，你留哪一段？',
    description: '时光的大浪淘沙里，哪一个瞬间是你无论如何都想铭刻在灵魂深处的？',
    task_type: 'question',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '初遇的惊艳、某次深夜的深情告白、或是确认关系的那一晚？',
  },
  {
    id: 'dt_268',
    title: '拍一张你背包挂件或钥匙扣的特写',
    description: '晃晃悠悠的小挂坠，是专属于你的个性小标识。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '挂在包上的毛绒小公仔或金属小挂件。',
  },
  {
    id: 'dt_269',
    title: '甜蜜清单：列出三件只要和对方在一起，就算发呆也很开心的事',
    description: '真正的默契不是不停说话，而是即使相对无言也感到无比踏实。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '一起靠在沙发上看电视、一起在超市推推车漫步…',
  },
  {
    id: 'dt_270',
    title: '魔性配音：挑一个对方平时最喜欢用的表情包，给它配上一句反差萌台词',
    description: '赋予静态表情包全新的灵魂，看看能不能让那个表情从此变得超搞笑。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '把严肃的表情配上极度撒娇的话，反差拉满！',
  },
  {
    id: 'dt_271',
    title: '聊聊我们第一次在现实中或者电话里互相说出「我想你」的情形',
    description: '三个字在嘴边徘徊了千百次，终于脱口而出的那一秒，耳朵都烧得滚烫。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '谁先说的？对方当时的停顿与回应是什么样的？',
  },
  {
    id: 'dt_272',
    title: '10 分钟正念细品食物',
    description: '安静吃一小颗坚果或一瓣橙子，专注感受食材在舌尖绽放的细腻风味。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '慢嚼细咽，重新发现食物的本味。',
  },
  {
    id: 'dt_273',
    title: '趣味设想：如果我们俩一起开一家社区小店，你希望是一家什么样的小店？',
    description: '跳出常规职场，想象一下你们俩作为合伙人的温馨日常营生。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '独立咖啡馆、深夜治愈居酒屋、街角鲜花绿植店、还是二手书店？',
  },
  {
    id: 'dt_274',
    title: '拍拍今天傍晚日落前最后一抹微光',
    description: '白昼将尽，夜色渐起，愿这一抹温柔夕阳抚平所有烦躁。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '天际线上淡淡的橙紫色晚霞。',
  },
  {
    id: 'dt_275',
    title: '睡前仪式：互道晚安前，各说一句今天对方最让自己动心的话',
    description: '带着被爱的踏实感沉入梦乡，连梦境都会变成棉花糖味道。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '把今天最甜的一句话当做枕边安眠曲。',
  },
  {
    id: 'dt_276',
    title: '奇妙动物邻居：如果家里的扫地机器人成精了，你觉得它会怎么吐槽我们？',
    description: '站在第三者观察视角，审视一下你们日常那些逗趣搞笑的生活小片段。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「这俩人天天坐在沙发上除了傻笑就是互相投喂零食！」',
  },
  {
    id: 'dt_277',
    title: '回忆对方做过的一个让你觉得「真拿 TA 没办法」的可爱撒娇瞬间',
    description: '遇到小无赖般的撒娇攻势，再坚硬的心脏也会在一秒钟之内化成温水。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '扯着你的衣角摇晃、嘟起嘴巴看着你、或是整个人赖在沙发上不肯动。',
  },
  {
    id: 'dt_278',
    title: '15 分钟手账与日记时光',
    description: '用几行文字或贴纸记下今天最深刻的一幕，把日子过成有痕迹的画册。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '在笔记本里留下今天的专属注脚。',
  },
  {
    id: 'dt_279',
    title: '关于独处：你觉得享受独处和渴望相聚之间，最好的舒适平衡点在哪儿？',
    description: '既是两个独立前行的个体，又是亲密无间的战友，聊聊你的空间感。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '各自在同一个房间里各忙各的、定期留出独自充电的时间…',
  },
  {
    id: 'dt_280',
    title: '拍一张两个杯子或者成双成对的小物件',
    description: '两个小东西挨在一起，就像我们无论相隔多远，心都在一起。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '并排的两个杯子、两双筷子或一对小摆件。',
  },
  {
    id: 'dt_281',
    title: '专属晚安吻：发送一个晚安吻表情包，伴着好梦入眠',
    description: '轻轻落在一个吻，隔着屏幕也能感受到嘴唇微温的笃定。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '挑一个最软萌的晚安表情，给今天盖个甜甜的章。',
  },
  {
    id: 'dt_282',
    title: '逆向语音翻译：用输入法语音转文字快速说一句含糊的话，看识别出什么神仙句子',
    description: '故意吐字不清或语速飞快，看看人工智能会理解出什么爆笑乌龙。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '把识别出来的搞笑火星文直接截图或复制发给 TA。',
  },
  {
    id: 'dt_283',
    title: '想想那家我们经常去、甚至老板都认识我们的宝藏小店',
    description: '小店里固定的角落桌位、每次必点的那几样老菜品，承载着无数回忆。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那家小店还在开吗？下次见面要不要再去吃一次？',
  },
  {
    id: 'dt_284',
    title: '20 分钟温和自我关照',
    description: '洗把脸，涂抹好保湿乳液，或者用热毛巾敷一敷酸胀的脖子。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '给疲惫了一天的身体一点温柔犒赏。',
  },
  {
    id: 'dt_285',
    title: '信任基石：你觉得两个人之间建立无条件的坚固信任，最关键的纽带是什么？',
    description: '坦诚不欺骗、说到做到、遇到分歧及时复盘沟通…',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '聊聊你在一段亲密关系中最看重的心底底线。',
  },
  {
    id: 'dt_286',
    title: '拍拍窗边微风吹拂的窗帘一角',
    description: '静止的房间里，有了风吹过的弧度，就有了呼吸的灵动。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '轻轻飘起的一角白色纱帘或布帘。',
  },
  {
    id: 'dt_287',
    title: '晨间心跳：早上醒来后，第一句想对 TA 说的话是什么？',
    description: '清晨睁开眼脑海里浮现的第一个人，必定是心里最牵挂的人。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「早安，今天醒来第一个想到的就是你。」',
  },
  {
    id: 'dt_288',
    title: '奇怪小收藏：聊聊你曾经迷恋并偷偷收集过什么让人无法理解的小玩意？',
    description: '每个人抽屉深处都藏着一些奇怪的执念，快交出你的秘密宝藏！',
    task_type: 'random',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '糖纸、雪糕棍、饮料瓶盖、形状奇怪的石头…',
  },
  {
    id: 'dt_289',
    title: '回忆我们曾经共同完成过的一件很有挑战的事（搬家/备考/打卡等）',
    description: '两个人拧成一股绳往前冲，攻坚克难后的击掌与庆祝分外珍贵。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那些流下的汗水、累瘫在地的时刻、以及彼此眼中的赞许。',
  },
  {
    id: 'dt_290',
    title: '25 分钟灵感写作',
    description: '不限格式与题材，任由思绪在纸上流淌，写下一段独属于你的短句。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '记录天马行空的灵感与碎片感受。',
  },
  {
    id: 'dt_291',
    title: '奇妙角色：如果我们要一起拍一部幽默家庭喜剧，谁是家里的搞怪担当？',
    description: '一个负责抖机灵出洋相，一个负责冷幽默翻白眼，生活每天都是脱口秀！',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '分析一下两个人各自的幽默细胞和家庭喜剧定位。',
  },
  {
    id: 'dt_292',
    title: '拍一张今天让你觉得很有设计感或可爱的小招牌',
    description: '街道上有趣的小店招牌，常常能点亮路人的目光。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '手写字体的咖啡馆招牌、路边可爱的指示牌。',
  },
  {
    id: 'dt_293',
    title: '给 TA 的礼物：在心里构想一件手工制作的小礼物，描述给 TA 听',
    description: '心意比价格更昂贵，如果你是手艺人，你想亲手为 TA 做什么？',
    task_type: 'interaction',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '一条亲手织的围巾、一本手工相册、或是一个小木雕。',
  },
  {
    id: 'dt_294',
    title: '荒谬哲学：如果天上下起的雨全部变成甜甜的饮料，你希望是什么口味？',
    description: '在天马行空的梦幻雨天里，出门打伞都得张大嘴巴接一口喝！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '冰红茶味、蜜桃乌龙味、还是奶香奶气的可可味？',
  },
  {
    id: 'dt_295',
    title: '还记得第一次在同一张桌子前并肩学习或工作时的微妙紧张感吗？',
    description: '视线偶尔交汇就忍不住想笑，偷偷瞄对方一眼，心里小鹿撞个不停。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '明明在做严肃的事，空气里却飘着若有若无的清甜香气。',
  },
  {
    id: 'dt_296',
    title: '10 分钟室内正念步行',
    description: '在房间或走廊慢慢走 100 步，清晰感知脚掌每一次落地与抬起的受力。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '步履平稳，心境自然跟着安定下来。',
  },
  {
    id: 'dt_297',
    title: '晨昏偏好：你觉得自己是晨型人还是夜猫子？最享受一天中的哪个时刻？',
    description: '清晨的第一缕晨曦，还是万籁俱寂的深夜？聊聊你的高效舒适区。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '早起空气清新的专注、还是深夜灵感迸发的心流？',
  },
  {
    id: 'dt_298',
    title: '拍拍你今晚准备盖的被子或枕头一角',
    description: '洗得干干净净、散发着阳光或柔顺剂味道的被窝，是最好的港湾。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '蓬松的枕头、柔软温暖的被子折角。',
  },
  {
    id: 'dt_299',
    title: '爱的确认：告诉对方你最喜欢被 TA 怎样亲切地称呼',
    description: '专属的昵称像一把小钥匙，一叫出来心里就会软绵绵的。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '名字的叠字、可爱的小笨蛋、还是专门的小外号？',
  },
  {
    id: 'dt_300',
    title: '恋爱使用说明书：写下一条关于「如何快速给炸毛的你顺毛」的独家指南',
    description: '把自己的出厂配置和操作手册交出来，方便对方日后精准排障！',
    task_type: 'random',
    action_type: 'input',
    category: '表达',
    prompt_hint: '「投喂一杯芝士奶盖，配合 3 次真诚夸奖即可迅速复位。」',
  },
  {
    id: 'dt_301',
    title: '聊聊我们曾经因为小小误会而闹出的乌龙大笑话',
    description: '以为对方生气了其实只是在犯困，以为丢了东西其实在对方兜里…',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '误会解开后两个人坐在长椅上笑到前仰后合的释然。',
  },
  {
    id: 'dt_302',
    title: '15 分钟慢速诗文朗读',
    description: '用温和轻缓的声音读一段舒缓优美的散文或诗歌，感受汉语的音律之美。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '字句出唇，连呼吸都变得柔和起来。',
  },
  {
    id: 'dt_303',
    title: '岁月愿景：等到我们头发都白了牙齿也掉了的时候，你最想和对方一起干嘛？',
    description: '一生一世的承诺，到老了变成两个慈祥有趣的老顽童，那该多幸福。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '坐在摇椅上听老歌、一起戴着老花镜给猫咪梳毛…',
  },
  {
    id: 'dt_304',
    title: '拍一张身边带爱心形状或者像爱心的小东西',
    description: '生活总在不经意处偷偷比心，找找身边的爱心暗号。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '心形的小树叶、两颗碰在一起的小水果或拉花。',
  },
  {
    id: 'dt_305',
    title: '专属温度：如果你们的爱有一种具体的温度，你觉得是几度？',
    description: '是 37 度的恒温拥抱，还是 100 度的沸腾热烈？聊聊你的体会。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '写下度数和背后温暖的理由。',
  },
  {
    id: 'dt_306',
    title: '预言大师：大胆预言一下对方 5 年后最可能沉迷的一个无聊中老年爱好',
    description: '互相调侃未来的生活趣味，看看 TA 会不会成为养花遛鸟大爷/大妈！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '沉迷盘手串、阳台种大葱、还是迷上公园太极拳？',
  },
  {
    id: 'dt_307',
    title: '回忆某次生病或不舒服时，对方端来温水或买来药的那份细心与挂念',
    description: '人在脆弱时感受到的温柔最难忘怀，那份甚至超过心疼自己的呵护。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '额头上敷上的温热毛巾、悄悄调暗的灯光、守护在床边的轻声细语。',
  },
  {
    id: 'dt_308',
    title: '20 分钟晚间收纳速战',
    description: '集中精力把换洗的衣服丢进洗衣篮，把散落的鞋子摆放整齐。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '利索收尾家务，换来整洁的环境。',
  },
  {
    id: 'dt_309',
    title: '难忘欢笑：回忆我们两个人在一起笑得最放肆、肚子都笑疼的一次是什么时候？',
    description: '放声大笑的治愈力量，那个完全抛弃偶像包袱的欢脱时刻。',
    task_type: 'question',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '究竟是因为一件多微不足道的小事引发的一场爆笑狂欢？',
  },
  {
    id: 'dt_310',
    title: '拍拍你今天刚拆开的一个快递或包装袋',
    description: '拆开包裹那一刻的期待感，今天收到了什么心仪小物呢？',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '刚撕开胶带的纸箱或新拿到手的小物件。',
  },
  {
    id: 'dt_311',
    title: '默契暗语：今天用三个字代替「我想你」，看看对方能不能猜出',
    description: '含蓄却深情的加密表达，真正的爱意就算捂住嘴巴也会从眼睛里跑出来。',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「看月亮」「喝奶茶」或是「下雪了」？',
  },
  {
    id: 'dt_312',
    title: '九宫格数字密码：发一段纯数字组合（如 999 444 2664），让对方破译情话',
    description: '用古老的手机按键拼音九宫格传情，体验复古解密的浪漫情调。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '输入对应的拼音按键，看能不能拼出那句甜甜的情话。',
  },
  {
    id: 'dt_313',
    title: '想想我们俩第一次为未来描绘蓝图时的那些纯真设想',
    description: '未来的小窝要漆成什么颜色、阳台要养多大一只猫、周末怎么分工做饭…',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那些看似平凡的柴米油盐构想，每一笔都填满了彼此的身影。',
  },
  {
    id: 'dt_314',
    title: '10 分钟远离纷扰模式',
    description: '把手机设置为勿扰模式 10 分钟，在这个小窗口里只留给自己安宁。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '不被外界随时打扰的专属安静时间。',
  },
  {
    id: 'dt_315',
    title: '关于包容：在一段长久相处的关系里，你觉得什么样的事情是最需要相互包容的？',
    description: '人无完人，磨合就是把棱角慢慢打磨成能够严丝合缝拥抱的弧度。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '生活习惯的微小差异、突如其来的小情绪、做事的不同节奏…',
  },
  {
    id: 'dt_316',
    title: '拍一张今天走过的长长走廊或小巷',
    description: '纵深延伸的走廊尽头，或许就藏着归途的光亮。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '公司安静的走廊、或是家楼下的小巷。',
  },
  {
    id: 'dt_317',
    title: '共同承诺：无论今天各自有多忙，都留出 10 分钟专属的聊天时间',
    description: '生活节奏再快，属于两个人的时钟也不能停摆，留一片独处的小天地。',
    task_type: 'interaction',
    action_type: 'input',
    category: '共同完成',
    prompt_hint: '约定好时间，放下手头杂事，专心陪 TA 说说话。',
  },
  {
    id: 'dt_318',
    title: '今日运势签：假装翻开今日情侣老黄历，给对方算一卦今天宜忌什么',
    description: '宜：想念对方、按时吃饭、早点入睡；忌：皱眉叹气、一个人扛事！',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '为对方定制今天专属的黄历吉签。',
  },
  {
    id: 'dt_319',
    title: '回忆我们一起拍的第一套搞怪大头贴或自拍连拍',
    description: '在狭窄的机器小格子里手忙脚乱摆姿势，留下最毫无包袱的鬼脸与笑容。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那些带搞笑贴纸的照片，现在还夹在哪一本手账或者相册里呢？',
  },
  {
    id: 'dt_320',
    title: '25 分钟沉浸益智小挑战',
    description: '专注做一道数独题、拼一张小拼图或解一道逻辑谜题，给大脑健健身。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '在思维的专注运转中感受纯粹乐趣。',
  },
  {
    id: 'dt_321',
    title: '心理年龄：抛开身份证上的数字，你觉得对方真实的心理年龄是几岁？',
    description: '有时候像运筹帷幄的可靠大人，有时候又像三岁半需要抱抱的小朋友！',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '说说你在什么时候觉得 TA 超成熟，什么时候觉得 TA 像个小孩。',
  },
  {
    id: 'dt_322',
    title: '拍拍手心向上托着一样小物件的照片',
    description: '伸出手掌，把手心的小美好隔空捧给对方看。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '手心里的一颗糖果、一朵小花或一枚硬币。',
  },
  {
    id: 'dt_323',
    title: '爱的回音壁：把对方曾经最常对你说的一句口头禅重复给 TA 听',
    description: '耳濡目染的习惯，是相处久了之后留在彼此身上最温柔的烙印。',
    task_type: 'interaction',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '学着 TA 的腔调，原汁原味复刻出来！',
  },
  {
    id: 'dt_324',
    title: '换装狂想曲：如果能强迫对方穿上一套奇装异服，你想看 TA 穿什么？',
    description: '满足自己的恶趣味脑洞，把对方打扮成全宇宙最引人注目的崽！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '恐龙充气服、大葱连体衣、或是可爱的睡衣斗篷？',
  },
  {
    id: 'dt_325',
    title: '聊聊那张虽然拍糊了、光线也不好，但你依然舍不得删掉的照片',
    description: '完美的照片留给外人看，而那些糊掉的、大笑的抓拍才是我们真实的生命温度。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '讲讲那张糊糊的照片背后，究竟发生了什么有趣的小插曲？',
  },
  {
    id: 'dt_326',
    title: '15 分钟选好明日行头',
    description: '提前选好明天出门要穿的衣服与鞋子，明早就能多睡 10 分钟。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '衣物搭配整齐，明天清爽启程。',
  },
  {
    id: 'dt_327',
    title: '心动瞬间：对方曾经做过哪个不经意的细小动作，瞬间击中了你的心脏？',
    description: '猝不及防的心跳漏了一拍，那一秒钟的电波至今想起来依然酥酥麻麻。',
    task_type: 'question',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '低头浅笑的一瞬间、顺手接过你手里重物的动作、回眸寻找你的眼神…',
  },
  {
    id: 'dt_328',
    title: '拍拍今天吃完后的空盘子或空杯子（光盘行动）',
    description: '认真吃完每一餐，是对食物的尊重，也是爱护身体的证明。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '吃得干干净净的碗底，夸夸自己是个干饭王。',
  },
  {
    id: 'dt_329',
    title: '宠爱特权：给对方颁发一张今天专属的「无条件撒娇券」',
    description: '持券者今天可以毫无顾忌地耍赖、要抱抱、提一个合理小要求！',
    task_type: 'interaction',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '「凭此券可无条件兑换一次捏脸或投喂！」',
  },
  {
    id: 'dt_330',
    title: '冷门恐惧点：除了昆虫蟑螂，你还有什么让人觉得匪夷所思的害怕事物？',
    description: '有些人的雷点千奇百怪，聊聊那些只有你自己懂的小小恐惧点。',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '害怕气球突然爆掉、害怕尖锐的铅笔尖、或是密恐？',
  },
  {
    id: 'dt_331',
    title: '回忆某次一起在深夜喝着热饮、漫无目的闲聊人生的畅快感受',
    description: '全世界都已经睡去，唯独你们俩还清醒着，分享着心底最真实的宇宙。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '夜深人静时的倾吐，让两颗心靠得前所未有的近。',
  },
  {
    id: 'dt_332',
    title: '20 分钟专注深读一本好书',
    description: '沉下心翻阅经典名著的一个章节，体会角色在字里行间的人生故事。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '关上手机，潜入书本营造的浩瀚世界。',
  },
  {
    id: 'dt_333',
    title: '同频共振：你觉得我们俩最大的一个共同点，和最大的一个互补点分别是什么？',
    description: '求同存异的智慧，共同点让我们心意相通，互补点让我们成为更强的双人组。',
    task_type: 'question',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '性格上的互补、兴趣爱好的重合、处理问题的风格差异…',
  },
  {
    id: 'dt_334',
    title: '拍一张镜子里露出一角手机壳的反射照',
    description: '不用露出正脸，看看你今天用的是哪个心爱的手机壳。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '镜子里反射的可爱手机壳与手部。',
  },
  {
    id: 'dt_335',
    title: '疲惫清零：告诉 TA「今天已经做得很好了，回家好好休息」',
    description: '成年人的世界不容易，有你这一句温柔的认可，所有委屈都能释怀。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '当 TA 疲惫时最管用的心理充电宝。',
  },
  {
    id: 'dt_336',
    title: '太空野餐计划：如果可以坐飞船去外太空野餐，你最想在哪个星球铺野餐垫？',
    description: '在浩瀚璀璨的星河里，找一颗属于你们两个人的浪漫野餐基地。',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '在月球上看地球升起、在土星环上数冰晶碎片…',
  },
  {
    id: 'dt_337',
    title: '还记得我们第一次一起坐摩天轮、缆车或看全城夜景的高光时刻吗？',
    description: '升到最高点时整个城市的霓虹都在脚下流淌，而你身旁就是整个世界。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那一刻的俯瞰与对视，仿佛时间都在高空为你们停留了片刻。',
  },
  {
    id: 'dt_338',
    title: '10 分钟转动眼球消除眼疲劳',
    description: '顺时针转 5 圈，逆时针转 5 圈，再望向窗外的绿色远山或树冠。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '释放眼肌压力，眼前视界重新清晰明亮。',
  },
  {
    id: 'dt_339',
    title: '幸福瞬间：今天这一整天里，哪一个细微的瞬间让你觉得「活着真好」？',
    description: '去感受日常里微风吹拂、饭菜飘香、或者一句问候带来的治愈感。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '下班走出大门吹到的微风、喝到第一口热汤的满足…',
  },
  {
    id: 'dt_340',
    title: '拍拍路边任何一片金黄或泛红的落叶',
    description: '四季更迭的讯号，就写在每一片飘落的叶脉之间。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '踩在路旁的一片干爽落叶。',
  },
  {
    id: 'dt_341',
    title: '晚安小夜灯：如果有一盏小夜灯整夜守护 TA，你希望它是什么形状？',
    description: '愿那抹微光驱散深夜里所有冰凉，把房间照得暖洋洋的。',
    task_type: 'interaction',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '小月亮、圆滚滚的胖橘猫、还是小面包形状？',
  },
  {
    id: 'dt_342',
    title: '出场自带 BGM：如果你走在路上会自带背景音乐，你觉得是什么风格？',
    description: '给自己的日常生活配上一段带感的电影原声带，气场两米八！',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '欢快的动画片小调、复古的爵士乐、还是热血的动漫摇滚？',
  },
  {
    id: 'dt_343',
    title: '回忆那件你们穿过的第一套情侣装，或者用过的第一对情侣配件',
    description: '走在街上暗戳戳昭告天下的那份小小骄傲，心里像喝了气泡水一样咕嘟冒泡。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '情侣手机壳、情侣帆布鞋、或是同款连帽衫…',
  },
  {
    id: 'dt_344',
    title: '25 分钟最难任务先完成',
    description: '先把最难啃的那块骨头搞定，接下来的时间就会变得格外轻松惬意。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '迎难而上，战胜心里的小逃避。',
  },
  {
    id: 'dt_345',
    title: '精神角落：当你在外面的世界感到疲惫时，BIBU！小窝对你来说意味着什么？',
    description: '在纷繁嘈杂的现实生活之外，这里是只属于两个人的隐秘桃源。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '分享你打开小窝那一刻，心底升起的那份安全感与归属感。',
  },
  {
    id: 'dt_346',
    title: '拍拍你今天最喜欢的一件小摆件',
    description: '桌上那个无论看多少次依然会让你会心一笑的小玩具。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '积木、盲盒手办、或是黏土小雕塑。',
  },
  {
    id: 'dt_347',
    title: '浪漫一笔：用诗意的一句话形容今晚的月色和你想念 TA 的心境',
    description: '今夜月色真美，而风也温柔，所有的浪漫最终都指向了你。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '借着月光，给心上人寄去一份典雅的浪漫。',
  },
  {
    id: 'dt_348',
    title: '手指秘密协议：设计一个专属的手指暗号，代表「我现在超需要你的安慰」',
    description: '在人多不方便说话的时候，勾勾手指就能瞬间接收彼此的脆弱与爱意。',
    task_type: 'random',
    action_type: 'input',
    category: '趣味挑战',
    prompt_hint: '用小拇指轻轻碰三下、或是掌心画一个小圆圈。',
  },
  {
    id: 'dt_349',
    title: '想想某次两个人互送手写卡片或小纸条时，信封里字句的温度',
    description: '在这个信息秒回的时代，一笔一划写在纸上的字迹承载着最沉甸甸的爱意。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '那些折成爱心的小纸条，现在还收纳在你的哪只铁盒子里？',
  },
  {
    id: 'dt_350',
    title: '15 分钟 4-7-8 呼吸平静法',
    description: '吸气 4 秒，屏气 7 秒，慢呼气 8 秒，连续 5 组，让心率沉稳下来。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '科学调节副交感神经，消除内心躁气。',
  },
  {
    id: 'dt_351',
    title: '恋爱初心：当初相处到哪一个节点时，让你在心里确信「就是这个人了」？',
    description: '那一刻的笃定不是一时冲动，而是千百个细节汇聚成的一道坚固心门。',
    task_type: 'question',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '聊天聊到舍不得挂电话、对方下意识的体贴照顾、价值观惊人一致的瞬间…',
  },
  {
    id: 'dt_352',
    title: '拍一张今天踩在落叶或草地上的脚部照片',
    description: '脚踏实地的触感，大自然总是最能让人放松紧绷的神经。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '鞋尖踩在草坪或沙沙作响的落叶堆上。',
  },
  {
    id: 'dt_353',
    title: '倾听心声：轻声问问对方「今天最想让我陪你聊点什么？」',
    description: '把话题的选择权完全交给对方，做 TA 最耐心、最包容的同频听众。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '无论天南海北的闲聊，还是严肃的规划，我都想听。',
  },
  {
    id: 'dt_354',
    title: '诚实大拷问：坦白一件你平时表面装得很懂、但其实完全一头雾水的事',
    description: '卸下坚强的伪装，在最爱的人面前承认自己其实也是个懵圈小白！',
    task_type: 'random',
    action_type: 'input',
    category: '分享',
    prompt_hint: '装作看懂了复杂的说明书、或者假装明白某个深奥的梗…',
  },
  {
    id: 'dt_355',
    title: '回忆那一次我们走在路上，突然不约而同哼出同一首歌的奇妙默契',
    description: '脑电波在无形中完成了一次精准对接，转头相视一眼，忍不住哈哈大笑。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '是什么歌？在什么样的场景下触发了这份奇妙的神奇共鸣？',
  },
  {
    id: 'dt_356',
    title: '20 分钟睡前舒缓休眠',
    description: '整理好床铺，熄灭大灯，开启一盏暗色小夜灯，互道晚安安心入梦。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '安静闭上眼，把今天交付给温柔的夜。',
  },
  {
    id: 'dt_357',
    title: '岁月长情：如果用一朵花或一棵树来形容我们的未来，你觉得会是什么？',
    description: '扎根于现实土壤，枝繁叶茂，共同抵御四季风霜。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '长青的松柏、温暖向阳的向日葵、幽香持久的茉莉、还是坚韧的橡树？',
  },
  {
    id: 'dt_358',
    title: '拍拍夜色中亮着暖黄色灯光的一扇窗户',
    description: '每一个亮着灯的窗口背后，都有一个温暖的归宿。',
    task_type: 'photo',
    action_type: 'photo',
    category: '观察',
    prompt_hint: '夜空下安静发光的一盏暖色窗灯。',
  },
  {
    id: 'dt_359',
    title: '专属拥护：坚定地告诉对方「不管外界怎么评判，我永远站在你这边」',
    description: '无条件的偏袒与爱意，是世界上最让人充满底气的安全感源泉。',
    task_type: 'interaction',
    action_type: 'input',
    category: '表达',
    prompt_hint: '你的肯定，就是 TA 抵御所有风雨最坚固的铠甲。',
  },
  {
    id: 'dt_360',
    title: '无厘头假设：如果今天有一只迷路的企鹅敲你家门，你第一反应会怎么做？',
    description: '面对突如其来的呆萌客人，展现你最真实、最无厘头的应对反应！',
    task_type: 'random',
    action_type: 'input',
    category: '小问题',
    prompt_hint: '给它开一罐金枪鱼罐头、还是拉着它一起跟对方视频通话？',
  },
  {
    id: 'dt_361',
    title: '聊聊那个曾经让你觉得「能够遇到 TA，真是太幸运了」的平凡瞬间',
    description: '不是轰轰烈烈的大事，就是某个再普通不过的转角，心里突然被感恩填得满满当当。',
    task_type: 'memory',
    action_type: 'input',
    category: '回忆',
    prompt_hint: '把那个瞬间的感恩与笃定，再次亲口复述给身旁的 TA 听吧。',
  },
  {
    id: 'dt_362',
    title: '15 分钟安静冥想呼吸',
    description: '端坐静心，观照自己每一次气息的出入，不作评判，全然接纳此刻。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '专注在当下的每一次心跳与呼吸中。',
  },
  {
    id: 'dt_363',
    title: '晚安发问：今晚闭上眼睛前，最想对屏幕对面的 TA 说的一句心里话是什么？',
    description: '让这句话成为今天最后的休止符，枕着爱意与被爱的温暖沉入香甜梦境。',
    task_type: 'question',
    action_type: 'input',
    category: '表达',
    prompt_hint: '一句真诚的晚安，胜过千万句世俗的喧嚣。',
  },
  {
    id: 'dt_364',
    title: '拍一张手比「耶」并映在墙上的可爱剪影',
    description: '借着台灯或阳光，在白墙上投下一个小小的胜利手势。',
    task_type: 'photo',
    action_type: 'photo',
    category: '照片',
    prompt_hint: '墙面上清晰又俏皮的双指小阴影。',
  },
  {
    id: 'dt_365',
    title: '20 分钟沉浸式舒展拉伸',
    description: '做一套全身关节与韧带的柔和伸展，伴随着轻柔的呼气释放所有僵硬。',
    task_type: 'focus',
    action_type: 'focus',
    category: '专注陪伴',
    prompt_hint: '让整个身躯恢复轻盈与通畅。',
  },
]
