export const eventArtGroups = [
  { id: 'all', label: '全部' },
  { id: 'friends', label: '小伙伴' },
  { id: 'daily', label: '恋爱日常' },
  { id: 'travel', label: '旅行自然' },
  { id: 'milestones', label: '节日纪念' },
  { id: 'growth', label: '成长目标' },
] as const
export type EventArtGroup = (typeof eventArtGroups)[number]['id']

export const eventArtOptions = [
  {
    id: 'heart',
    label: '恋爱心动',
    category: '恋爱纪念',
    tone: 'pink',
    group: 'daily',
    keywords: '喜欢 爱情 表白 love',
  },
  {
    id: 'bunny',
    label: '送信小兔',
    category: '想见你',
    tone: 'pink',
    group: 'friends',
    keywords: '兔子 兔兔 rabbit bunny',
  },
  {
    id: 'dog',
    label: '出游小狗',
    category: '一起出发',
    tone: 'yellow',
    group: 'friends',
    keywords: '狗狗 小狗 puppy dog',
  },
  {
    id: 'cat',
    label: '橘子小猫',
    category: '猫系陪伴',
    tone: 'yellow',
    group: 'friends',
    keywords: '猫咪 橘猫 cat',
  },
  {
    id: 'bear',
    label: '抱抱小熊',
    category: '温柔拥抱',
    tone: 'yellow',
    group: 'friends',
    keywords: '熊熊 玩偶 bear',
  },
  {
    id: 'penguin',
    label: '围巾企鹅',
    category: '暖暖陪伴',
    tone: 'blue',
    group: 'friends',
    keywords: '企鹅 冬天 penguin',
  },
  {
    id: 'fox',
    label: '机灵狐狸',
    category: '小小冒险',
    tone: 'yellow',
    group: 'friends',
    keywords: '狐狸 小狐 fox',
  },
  {
    id: 'frog',
    label: '快乐青蛙',
    category: '元气满满',
    tone: 'green',
    group: 'friends',
    keywords: '青蛙 蛙蛙 frog',
  },
  {
    id: 'duck',
    label: '散步小鸭',
    category: '一起散步',
    tone: 'yellow',
    group: 'friends',
    keywords: '鸭子 小鸭 duck',
  },
  {
    id: 'cake',
    label: '生日蛋糕',
    category: '生日快乐',
    tone: 'lilac',
    group: 'milestones',
    keywords: '生日 蛋糕 庆祝 cake birthday',
  },
  {
    id: 'sea',
    label: '海边假期',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '看海 沙滩 度假 sea beach',
  },
  {
    id: 'train',
    label: '见面列车',
    category: '奔向彼此',
    tone: 'green',
    group: 'travel',
    keywords: '高铁 火车 见面 train',
  },
  {
    id: 'plane',
    label: '旅行飞机',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '飞机 旅游 出国 plane flight',
  },
  {
    id: 'trophy',
    label: '里程奖杯',
    category: '特别里程',
    tone: 'yellow',
    group: 'milestones',
    keywords: '成就 奖杯 纪念 trophy',
  },
  {
    id: 'gift',
    label: '惊喜礼物',
    category: '小小惊喜',
    tone: 'pink',
    group: 'milestones',
    keywords: '礼物 送礼 惊喜 gift',
  },
  {
    id: 'coffee',
    label: '咖啡约会',
    category: '日常约会',
    tone: 'green',
    group: 'daily',
    keywords: '咖啡 奶茶 饮料 coffee',
  },
  {
    id: 'tree',
    label: '节日小树',
    category: '节日约定',
    tone: 'green',
    group: 'milestones',
    keywords: '圣诞 节日 树 christmas',
  },
  {
    id: 'home',
    label: '一起回家',
    category: '共同生活',
    tone: 'yellow',
    group: 'daily',
    keywords: '新家 搬家 同居 home',
  },
  {
    id: 'book',
    label: '一起读书',
    category: '共同成长',
    tone: 'blue',
    group: 'growth',
    keywords: '学习 考试 考研 阅读 读书 book study',
  },
  {
    id: 'briefcase',
    label: '工作加油',
    category: '工作目标',
    tone: 'yellow',
    group: 'growth',
    keywords: '工作 入职 实习 转正 work job',
  },
  {
    id: 'code',
    label: '编程搭子',
    category: '一起创造',
    tone: 'green',
    group: 'growth',
    keywords: '编程 代码 项目 coding code',
  },
  {
    id: 'flag',
    label: '目标达成',
    category: '一起冲刺',
    tone: 'pink',
    group: 'growth',
    keywords: '考试 考研 目标 计划 flag goal',
  },
  {
    id: 'dumbbell',
    label: '运动打卡',
    category: '健康陪伴',
    tone: 'blue',
    group: 'growth',
    keywords: '健身 运动 肌肉 训练 gym fitness',
  },
  {
    id: 'bicycle',
    label: '周末骑行',
    category: '运动出游',
    tone: 'green',
    group: 'growth',
    keywords: '单车 自行车 骑行 bike cycling',
  },
  {
    id: 'camera',
    label: '拍照留念',
    category: '收藏瞬间',
    tone: 'lilac',
    group: 'daily',
    keywords: '摄影 相机 合照 写真 camera photo',
  },
  {
    id: 'music',
    label: '音乐现场',
    category: '一起听歌',
    tone: 'pink',
    group: 'daily',
    keywords: '音乐 演唱会 歌曲 concert music',
  },
  {
    id: 'headphone',
    label: '共享耳机',
    category: '同频时刻',
    tone: 'blue',
    group: 'daily',
    keywords: '听歌 耳机 播客 headphone',
  },
  {
    id: 'gamepad',
    label: '双人游戏',
    category: '快乐双排',
    tone: 'lilac',
    group: 'daily',
    keywords: '游戏 手柄 双排 game',
  },
  {
    id: 'movie',
    label: '电影之夜',
    category: '一起观影',
    tone: 'yellow',
    group: 'daily',
    keywords: '电影 影院 追剧 movie film',
  },
  {
    id: 'shopping',
    label: '逛街约会',
    category: '日常约会',
    tone: 'pink',
    group: 'daily',
    keywords: '购物 逛街 买衣服 shopping',
  },
  {
    id: 'flower',
    label: '送你小花',
    category: '浪漫日常',
    tone: 'pink',
    group: 'daily',
    keywords: '花朵 鲜花 花束 flower',
  },
  {
    id: 'icecream',
    label: '冰淇淋日',
    category: '甜甜日常',
    tone: 'lilac',
    group: 'daily',
    keywords: '冰激凌 冰淇淋 甜品 ice cream',
  },
  {
    id: 'sun',
    label: '一起看日出',
    category: '晴天出游',
    tone: 'yellow',
    group: 'travel',
    keywords: '日出 太阳 晴天 sun sunrise',
  },
  {
    id: 'moon',
    label: '月亮晚安',
    category: '月下约定',
    tone: 'blue',
    group: 'travel',
    keywords: '月亮 晚安 星夜 moon night',
  },
  {
    id: 'mountain',
    label: '一起爬山',
    category: '山野出游',
    tone: 'green',
    group: 'travel',
    keywords: '爬山 登山 远足 mountain hiking',
  },
  {
    id: 'tent',
    label: '星空露营',
    category: '户外约定',
    tone: 'green',
    group: 'travel',
    keywords: '露营 帐篷 户外 tent camping',
  },
  {
    id: 'compass',
    label: '探索地图',
    category: '一起冒险',
    tone: 'yellow',
    group: 'travel',
    keywords: '指南针 探索 导航 compass',
  },
  {
    id: 'backpack',
    label: '背包出发',
    category: '周末旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '背包 远行 旅行 backpack trip',
  },
  {
    id: 'star',
    label: '闪闪发光',
    category: '特别时刻',
    tone: 'yellow',
    group: 'milestones',
    keywords: '星星 星光 成就 star',
  },
  {
    id: 'balloon',
    label: '庆祝气球',
    category: '快乐庆祝',
    tone: 'pink',
    group: 'milestones',
    keywords: '气球 聚会 派对 balloon party',
  },
  {
    id: 'fish',
    label: '吐泡泡鱼',
    category: '水族乐园',
    tone: 'blue',
    group: 'friends',
    keywords: '小鱼 金鱼 热带鱼 海洋馆 潜水 fish',
  },
  {
    id: 'robot',
    label: '快乐机甲',
    category: '机械搭档',
    tone: 'blue',
    group: 'friends',
    keywords: '机器人 机甲 伴侣搭档 守护 robot bot',
  },
  {
    id: 'tea',
    label: '暖暖热茶',
    category: '慢品日常',
    tone: 'green',
    group: 'daily',
    keywords: '喝茶 热茶 奶茶 下午茶 慢生活 养生 tea',
  },
  {
    id: 'apple',
    label: '甜甜苹果',
    category: '甜甜日常',
    tone: 'pink',
    group: 'daily',
    keywords: '苹果 水果 水果捞 甜甜 健康 平安 apple fruit',
  },
  {
    id: 'wine',
    label: '浪漫微醺',
    category: '烛光晚餐',
    tone: 'pink',
    group: 'daily',
    keywords: '红酒 喝酒 微醺 晚宴 烛光 约会 庆祝 wine bottle',
  },
  {
    id: 'mail',
    label: '悄悄纸条',
    category: '纸短情长',
    tone: 'pink',
    group: 'daily',
    keywords: '写信 情书 明信片 纸条 留言 邮票 mail letter',
  },
  {
    id: 'bed',
    label: '周末赖床',
    category: '慵懒时光',
    tone: 'lilac',
    group: 'daily',
    keywords: '睡觉 赖床 休息 晚安 早安 补觉 抱抱 bed sleep',
  },
  {
    id: 'clock',
    label: '晨光闹钟',
    category: '早安打卡',
    tone: 'yellow',
    group: 'daily',
    keywords: '闹钟 起床 早起 时间 打卡 守候 早安 clock time',
  },
  {
    id: 'car',
    label: '自驾出游',
    category: '公路旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '开车 自驾 公路 兜风 出发 沿海公路 car trip',
  },
  {
    id: 'bus',
    label: '漫游巴士',
    category: '城市漫游',
    tone: 'green',
    group: 'travel',
    keywords: '公交 巴士 兜风 城市 散步 观光 bus',
  },
  {
    id: 'ship',
    label: '轮渡出海',
    category: '乘船远行',
    tone: 'blue',
    group: 'travel',
    keywords: '游轮 轮渡 乘船 出海 航行 看海 ship boat',
  },
  {
    id: 'earth',
    label: '环球漫游',
    category: '走遍世界',
    tone: 'blue',
    group: 'travel',
    keywords: '世界 地球 环游 出国 远方 梦想 earth globe',
  },
  {
    id: 'fire',
    label: '营地篝火',
    category: '温暖陪伴',
    tone: 'yellow',
    group: 'travel',
    keywords: '营火 篝火 露营 温暖 围炉 烤肉 暖冬 fire camp',
  },
  {
    id: 'cloud',
    label: '晴空云朵',
    category: '好天气',
    tone: 'blue',
    group: 'travel',
    keywords: '云朵 天空 晴天 散步 阳光 好天气 cloud',
  },
  {
    id: 'party',
    label: '撒花庆祝',
    category: '惊喜派对',
    tone: 'pink',
    group: 'milestones',
    keywords: '派对 撒花 庆祝 狂欢 惊喜 欢呼 礼花 party popper',
  },
  {
    id: 'crown',
    label: '专属加冕',
    category: '特别仪式',
    tone: 'yellow',
    group: 'milestones',
    keywords: '王冠 皇冠 仪式 公主 王子 专属 加冕 crown',
  },
  {
    id: 'gem',
    label: '璀璨心意',
    category: '珍贵誓约',
    tone: 'blue',
    group: 'milestones',
    keywords: '钻石 宝石 珍贵 誓约 戒指 心意 璀璨 diamond gem',
  },
  {
    id: 'bell',
    label: '幸福钟声',
    category: '甜蜜誓约',
    tone: 'yellow',
    group: 'milestones',
    keywords: '铃铛 钟声 仪式 祝福 幸福 婚礼 敲钟 bell',
  },
  {
    id: 'coins',
    label: '恋爱金库',
    category: '共同储蓄',
    tone: 'yellow',
    group: 'milestones',
    keywords: '存钱 金币 储蓄 梦想 基金 攒钱 理财 coins money',
  },
  {
    id: 'pencil',
    label: '共同创作',
    category: '手绘时光',
    tone: 'yellow',
    group: 'growth',
    keywords: '写字 画画 记录 笔记 创作 手帐 临摹 pencil draw',
  },
  {
    id: 'shield',
    label: '守护彼此',
    category: '安全感',
    tone: 'blue',
    group: 'growth',
    keywords: '保护 守护 安全 依靠 陪伴 避风港 shield',
  },
  {
    id: 'potion',
    label: '能量药水',
    category: '元气补给',
    tone: 'pink',
    group: 'growth',
    keywords: '魔法 药水 补给 活力 治愈 加油 回血 potion magic',
  },
  {
    id: 'sparkles',
    label: '闪耀奇迹',
    category: '高光时刻',
    tone: 'yellow',
    group: 'growth',
    keywords: '魔法 闪光 闪耀 奇迹 闪闪 发光 耀眼 sparkles shine',
  },
  {
    id: 'hourglass',
    label: '倒数时光',
    category: '珍惜当下',
    tone: 'lilac',
    group: 'growth',
    keywords: '沙漏 倒计时 时间 珍惜 等待 倒数 时光 hourglass time',
  },
] as const
export type EventArtId = (typeof eventArtOptions)[number]['id']
// Keep the existing DB field and CHECK length. Old emoji values render as SVG;
// new choices store stable identifiers, never executable markup or URLs.
const legacy: Record<string, EventArtId> = {
  '💛': 'heart',
  '♥': 'heart',
  '💗': 'heart',
  '🌊': 'sea',
  '🎂': 'cake',
  '🚃': 'train',
  '✈️': 'plane',
  '🎓': 'trophy',
  '🎄': 'tree',
  '🏠': 'home',
}
export function eventArtId(value: string): EventArtId {
  const id = value.replace(/^icon:/, '')
  return eventArtOptions.find((option) => option.id === id)?.id || legacy[value] || 'heart'
}
export function eventArtConfig(value: string) {
  return eventArtOptions.find((option) => option.id === eventArtId(value))!
}

export function filterEventArt(group: EventArtGroup, query: string) {
  const words = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)
  return eventArtOptions.filter((option) => {
    const text =
      `${option.label} ${option.category} ${option.keywords} ${option.id}`.toLocaleLowerCase()
    return (group === 'all' || option.group === group) && words.every((word) => text.includes(word))
  })
}
