export const eventArtGroups = [
  { id: 'all', label: '全部' },
  { id: 'milestones', label: '浪漫纪念' },
  { id: 'food', label: '美食甜点' },
  { id: 'travel', label: '旅行户外' },
  { id: 'daily', label: '温馨日常' },
  { id: 'growth', label: '兴趣成长' },
  { id: 'friends', label: '萌宠伙伴' },
] as const
export type EventArtGroup = (typeof eventArtGroups)[number]['id']

export const eventArtOptions = [
  {
    id: 'heart',
    label: '恋爱心动',
    category: '恋爱纪念',
    tone: 'pink',
    group: 'milestones',
    keywords: '喜欢 爱情 表白 love',
  },
  {
    id: 'bunny',
    label: '送信小兔',
    category: '想见你',
    tone: 'pink',
    group: 'friends',
    keywords: '兔子 兔兔 rabbit bunny',
  },
  {
    id: 'dog',
    label: '出游小狗',
    category: '一起出发',
    tone: 'yellow',
    group: 'friends',
    keywords: '狗狗 小狗 puppy dog',
  },
  {
    id: 'cat',
    label: '橘子小猫',
    category: '猫系陪伴',
    tone: 'yellow',
    group: 'friends',
    keywords: '猫咪 橘猫 cat',
  },
  {
    id: 'bear',
    label: '抱抱小熊',
    category: '温柔拥抱',
    tone: 'yellow',
    group: 'friends',
    keywords: '熊熊 玩偶 bear',
  },
  {
    id: 'penguin',
    label: '围巾企鹅',
    category: '暖暖陪伴',
    tone: 'blue',
    group: 'friends',
    keywords: '企鹅 冬天 penguin',
  },
  {
    id: 'fox',
    label: '机灵狐狸',
    category: '小小冒险',
    tone: 'yellow',
    group: 'friends',
    keywords: '狐狸 小狐 fox',
  },
  {
    id: 'frog',
    label: '快乐青蛙',
    category: '元气满满',
    tone: 'green',
    group: 'friends',
    keywords: '青蛙 蛙蛙 frog',
  },
  {
    id: 'duck',
    label: '散步小鸭',
    category: '一起散步',
    tone: 'yellow',
    group: 'friends',
    keywords: '鸭子 小鸭 duck',
  },
  {
    id: 'cake',
    label: '生日蛋糕',
    category: '生日快乐',
    tone: 'lilac',
    group: 'milestones',
    keywords: '生日 蛋糕 庆祝 cake birthday',
  },
  {
    id: 'sea',
    label: '海边假期',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '看海 沙滩 度假 sea beach',
  },
  {
    id: 'train',
    label: '见面列车',
    category: '奔向彼此',
    tone: 'green',
    group: 'travel',
    keywords: '高铁 火车 见面 train',
  },
  {
    id: 'plane',
    label: '旅行飞机',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '飞机 旅游 出国 plane flight',
  },
  {
    id: 'trophy',
    label: '里程奖杯',
    category: '特别里程',
    tone: 'yellow',
    group: 'milestones',
    keywords: '成就 奖杯 纪念 trophy',
  },
  {
    id: 'gift',
    label: '惊喜礼物',
    category: '小小惊喜',
    tone: 'pink',
    group: 'milestones',
    keywords: '礼物 送礼 惊喜 gift',
  },
  {
    id: 'coffee',
    label: '咖啡约会',
    category: '日常约会',
    tone: 'green',
    group: 'food',
    keywords: '咖啡 奶茶 饮料 coffee',
  },
  {
    id: 'tree',
    label: '节日小树',
    category: '节日约定',
    tone: 'green',
    group: 'milestones',
    keywords: '圣诞 节日 树 christmas',
  },
  {
    id: 'home',
    label: '一起回家',
    category: '共同生活',
    tone: 'yellow',
    group: 'daily',
    keywords: '新家 搬家 同居 home',
  },
  {
    id: 'book',
    label: '一起读书',
    category: '共同成长',
    tone: 'blue',
    group: 'growth',
    keywords: '学习 考试 考研 阅读 读书 book study',
  },
  {
    id: 'briefcase',
    label: '工作加油',
    category: '工作目标',
    tone: 'yellow',
    group: 'growth',
    keywords: '工作 入职 实习 转正 work job',
  },
  {
    id: 'code',
    label: '编程搭子',
    category: '一起创造',
    tone: 'green',
    group: 'growth',
    keywords: '编程 代码 项目 coding code',
  },
  {
    id: 'flag',
    label: '目标达成',
    category: '一起冲刺',
    tone: 'pink',
    group: 'growth',
    keywords: '考试 考研 目标 计划 flag goal',
  },
  {
    id: 'dumbbell',
    label: '运动打卡',
    category: '健康陪伴',
    tone: 'blue',
    group: 'growth',
    keywords: '健身 运动 肌肉 训练 gym fitness',
  },
  {
    id: 'bicycle',
    label: '周末骑行',
    category: '运动出游',
    tone: 'green',
    group: 'growth',
    keywords: '单车 自行车 骑行 bike cycling',
  },
  {
    id: 'camera',
    label: '拍照留念',
    category: '收藏瞬间',
    tone: 'lilac',
    group: 'daily',
    keywords: '摄影 相机 合照 写真 camera photo',
  },
  {
    id: 'music',
    label: '音乐现场',
    category: '一起听歌',
    tone: 'pink',
    group: 'growth',
    keywords: '音乐 演唱会 歌曲 concert music',
  },
  {
    id: 'headphone',
    label: '共享耳机',
    category: '同频时刻',
    tone: 'blue',
    group: 'growth',
    keywords: '听歌 耳机 播客 headphone',
  },
  {
    id: 'gamepad',
    label: '双人游戏',
    category: '快乐双排',
    tone: 'lilac',
    group: 'growth',
    keywords: '游戏 手柄 双排 game',
  },
  {
    id: 'movie',
    label: '电影之夜',
    category: '一起观影',
    tone: 'yellow',
    group: 'growth',
    keywords: '电影 影院 追剧 movie film',
  },
  {
    id: 'shopping',
    label: '逛街约会',
    category: '日常约会',
    tone: 'pink',
    group: 'daily',
    keywords: '购物 逛街 买衣服 shopping',
  },
  {
    id: 'flower',
    label: '送你小花',
    category: '浪漫日常',
    tone: 'pink',
    group: 'daily',
    keywords: '花朵 鲜花 花束 flower',
  },
  {
    id: 'icecream',
    label: '冰淇淋日',
    category: '甜甜日常',
    tone: 'lilac',
    group: 'food',
    keywords: '冰激凌 冰淇淋 甜品 ice cream',
  },
  {
    id: 'sun',
    label: '一起看日出',
    category: '晴天出游',
    tone: 'yellow',
    group: 'travel',
    keywords: '日出 太阳 晴天 sun sunrise',
  },
  {
    id: 'moon',
    label: '月亮晚安',
    category: '月下约定',
    tone: 'blue',
    group: 'travel',
    keywords: '月亮 晚安 星夜 moon night',
  },
  {
    id: 'mountain',
    label: '一起爬山',
    category: '山野出游',
    tone: 'green',
    group: 'travel',
    keywords: '爬山 登山 远足 mountain hiking',
  },
  {
    id: 'tent',
    label: '星空露营',
    category: '户外约定',
    tone: 'green',
    group: 'travel',
    keywords: '露营 帐篷 户外 tent camping',
  },
  {
    id: 'compass',
    label: '探索地图',
    category: '一起冒险',
    tone: 'yellow',
    group: 'travel',
    keywords: '指南针 探索 导航 compass',
  },
  {
    id: 'backpack',
    label: '背包出发',
    category: '周末旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '背包 远行 旅行 backpack trip',
  },
  {
    id: 'star',
    label: '闪闪发光',
    category: '特别时刻',
    tone: 'yellow',
    group: 'milestones',
    keywords: '星星 星光 成就 star',
  },
  {
    id: 'balloon',
    label: '庆祝气球',
    category: '快乐庆祝',
    tone: 'pink',
    group: 'milestones',
    keywords: '气球 聚会 派对 balloon party',
  },
  {
    id: 'fish',
    label: '吐泡泡鱼',
    category: '水族乐园',
    tone: 'blue',
    group: 'friends',
    keywords: '小鱼 金鱼 热带鱼 海洋馆 潜水 fish',
  },
  {
    id: 'robot',
    label: '快乐机甲',
    category: '机械搭档',
    tone: 'blue',
    group: 'friends',
    keywords: '机器人 机甲 伴侣搭档 守护 robot bot',
  },
  {
    id: 'tea',
    label: '暖暖热茶',
    category: '慢品日常',
    tone: 'green',
    group: 'food',
    keywords: '喝茶 热茶 奶茶 下午茶 慢生活 养生 tea',
  },
  {
    id: 'apple',
    label: '甜甜苹果',
    category: '甜甜日常',
    tone: 'pink',
    group: 'food',
    keywords: '苹果 水果 水果捞 甜甜 健康 平安 apple fruit',
  },
  {
    id: 'wine',
    label: '浪漫微醺',
    category: '烛光晚餐',
    tone: 'pink',
    group: 'food',
    keywords: '红酒 喝酒 微醺 晚宴 烛光 约会 庆祝 wine bottle',
  },
  {
    id: 'mail',
    label: '悄悄纸条',
    category: '纸短情长',
    tone: 'pink',
    group: 'daily',
    keywords: '写信 情书 明信片 纸条 留言 邮票 mail letter',
  },
  {
    id: 'bed',
    label: '周末赖床',
    category: '慵懒时光',
    tone: 'lilac',
    group: 'daily',
    keywords: '睡觉 赖床 休息 晚安 早安 补觉 抱抱 bed sleep',
  },
  {
    id: 'clock',
    label: '晨光闹钟',
    category: '早安打卡',
    tone: 'yellow',
    group: 'daily',
    keywords: '闹钟 起床 早起 时间 打卡 守候 早安 clock time',
  },
  {
    id: 'car',
    label: '自驾出游',
    category: '公路旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '开车 自驾 公路 兜风 出发 沿海公路 car trip',
  },
  {
    id: 'bus',
    label: '漫游巴士',
    category: '城市漫游',
    tone: 'green',
    group: 'travel',
    keywords: '公交 巴士 兜风 城市 散步 观光 bus',
  },
  {
    id: 'ship',
    label: '轮渡出海',
    category: '乘船远行',
    tone: 'blue',
    group: 'travel',
    keywords: '游轮 轮渡 乘船 出海 航行 看海 ship boat',
  },
  {
    id: 'earth',
    label: '环球漫游',
    category: '走遍世界',
    tone: 'blue',
    group: 'travel',
    keywords: '世界 地球 环游 出国 远方 梦想 earth globe',
  },
  {
    id: 'fire',
    label: '营地篝火',
    category: '温暖陪伴',
    tone: 'yellow',
    group: 'growth',
    keywords: '营火 篝火 露营 温暖 围炉 烤肉 暖冬 fire camp',
  },
  {
    id: 'cloud',
    label: '晴空云朵',
    category: '好天气',
    tone: 'blue',
    group: 'travel',
    keywords: '云朵 天空 晴天 散步 阳光 好天气 cloud',
  },
  {
    id: 'party',
    label: '撒花庆祝',
    category: '惊喜派对',
    tone: 'pink',
    group: 'milestones',
    keywords: '派对 撒花 庆祝 狂欢 惊喜 欢呼 礼花 party popper',
  },
  {
    id: 'crown',
    label: '专属加冕',
    category: '特别仪式',
    tone: 'yellow',
    group: 'milestones',
    keywords: '王冠 皇冠 仪式 公主 王子 专属 加冕 crown',
  },
  {
    id: 'gem',
    label: '璀璨心意',
    category: '珍贵誓约',
    tone: 'blue',
    group: 'milestones',
    keywords: '钻石 宝石 珍贵 誓约 戒指 心意 璀璨 diamond gem',
  },
  {
    id: 'bell',
    label: '幸福钟声',
    category: '甜蜜誓约',
    tone: 'yellow',
    group: 'milestones',
    keywords: '铃铛 钟声 仪式 祝福 幸福 婚礼 敲钟 bell',
  },
  {
    id: 'coins',
    label: '恋爱金库',
    category: '共同储蓄',
    tone: 'yellow',
    group: 'milestones',
    keywords: '存钱 金币 储蓄 梦想 基金 攒钱 理财 coins money',
  },
  {
    id: 'pencil',
    label: '共同创作',
    category: '手绘时光',
    tone: 'yellow',
    group: 'growth',
    keywords: '写字 画画 记录 笔记 创作 手帐 临摹 pencil draw',
  },
  {
    id: 'shield',
    label: '守护彼此',
    category: '安全感',
    tone: 'blue',
    group: 'growth',
    keywords: '保护 守护 安全 依靠 陪伴 避风港 shield',
  },
  {
    id: 'potion',
    label: '能量药水',
    category: '元气补给',
    tone: 'pink',
    group: 'growth',
    keywords: '魔法 药水 补给 活力 治愈 加油 回血 potion magic',
  },
  {
    id: 'sparkles',
    label: '闪耀奇迹',
    category: '高光时刻',
    tone: 'yellow',
    group: 'growth',
    keywords: '魔法 闪光 闪耀 奇迹 闪闪 发光 耀眼 sparkles shine',
  },
  {
    id: 'hourglass',
    label: '倒数时光',
    category: '珍惜当下',
    tone: 'lilac',
    group: 'growth',
    keywords: '沙漏 倒计时 时间 珍惜 等待 倒数 时光 hourglass time',
  },

  // ================= 100 款精选情侣与生活期待 SVG 素材 =================
  // 1-20: 美食甜点
  { id: 'hotpot', label: '咕嘟火锅', category: '暖心美食', tone: 'pink', group: 'food', keywords: '火锅 聚餐 热气 沸腾 冬天 辣椒 肥牛 hotpot' },
  { id: 'bbq', label: '夏夜烤肉', category: '风味小食', tone: 'yellow', group: 'food', keywords: '烧烤 烤肉 烤串 孜然 啤酒 夜市 bbq grill' },
  { id: 'sushi', label: '精致寿司', category: '浪漫大餐', tone: 'pink', group: 'food', keywords: '寿司 日料 三文鱼 饭团 刺身 日本料理 sushi' },
  { id: 'ramen', label: '日式拉面', category: '暖心美食', tone: 'yellow', group: 'food', keywords: '拉面 溏心蛋 叉烧 鸣门卷 面条 骨汤 ramen noodle' },
  { id: 'milktea', label: '珍珠奶茶', category: '甜蜜饮品', tone: 'yellow', group: 'food', keywords: '奶茶 珍珠 波霸 甜分 快乐水 下午茶 boba milktea' },
  { id: 'pizza', label: '芝士披萨', category: '分享快乐', tone: 'yellow', group: 'food', keywords: '披萨 芝士 拉丝 意式 快餐 聚会 pizza cheese' },
  { id: 'burger', label: '双层汉堡', category: '大口满足', tone: 'yellow', group: 'food', keywords: '汉堡 汉堡包 牛肉 薯条 快乐套餐 burger' },
  { id: 'donut', label: '草莓甜甜圈', category: '甜蜜甜点', tone: 'pink', group: 'food', keywords: '甜甜圈 糖霜 草莓 甜品 少女心 烘焙 donut' },
  { id: 'popcorn', label: '影院爆米花', category: '观影伴侣', tone: 'yellow', group: 'food', keywords: '爆米花 电影 影院 奶油 焦糖 零食 popcorn' },
  { id: 'baking', label: '手作烘焙', category: '温暖手作', tone: 'yellow', group: 'food', keywords: '面包 可颂 烘焙 烤箱 麦香 面包店 bread baking' },
  { id: 'cocktail', label: '清新特调', category: '浪漫小酌', tone: 'blue', group: 'food', keywords: '鸡尾酒 特调 调酒 酒吧 夜晚 碰杯 cocktail bar' },
  { id: 'pancake', label: '舒芙蕾松饼', category: '元气早餐', tone: 'yellow', group: 'food', keywords: '松饼 舒芙蕾 枫糖 黄油 早午餐 甜点 pancake' },
  { id: 'cherry', label: '双蒂樱桃', category: '鲜果时光', tone: 'pink', group: 'food', keywords: '樱桃 车厘子 水果 甜蜜 红色 双人 cherry' },
  { id: 'strawberry', label: '甜心草莓', category: '鲜果时光', tone: 'pink', group: 'food', keywords: '草莓 水果 甜心 采摘 冬日草莓 strawberry' },
  { id: 'watermelon', label: '冰镇西瓜', category: '夏日解暑', tone: 'pink', group: 'food', keywords: '西瓜 夏天 冰镇 清甜 解暑 盛夏 watermelon' },
  { id: 'dumpling', label: '热腾水饺', category: '传统佳肴', tone: 'yellow', group: 'food', keywords: '水饺 饺子 冬至 过年 团圆 包饺子 dumpling' },
  { id: 'taco', label: '香脆卷饼', category: '异域风味', tone: 'yellow', group: 'food', keywords: '塔可 卷饼 玉米饼 墨西哥 美食 taco' },
  { id: 'bento', label: '爱心便当', category: '甜蜜手作', tone: 'pink', group: 'food', keywords: '便当 爱心 野餐 盒饭 手作 料理 bento' },
  { id: 'fondue', label: '浓醇火锅', category: '甜蜜甜点', tone: 'yellow', group: 'food', keywords: '巧克力 芝士火锅 甜品 浓郁 棉花糖 fondue' },
  { id: 'macaron', label: '彩虹马卡龙', category: '法式甜点', tone: 'pink', group: 'food', keywords: '马卡龙 甜点 下午茶 法式 少女心 酥胸 macaron' },

  // 21-40: 约会旅行与户外
  { id: 'ferriswheel', label: '浪漫摩天轮', category: '游乐约会', tone: 'pink', group: 'travel', keywords: '摩天轮 游乐园 俯瞰 浪漫 约会 高空 ferris wheel' },
  { id: 'carousel', label: '旋转木马', category: '童话游乐', tone: 'yellow', group: 'travel', keywords: '旋转木马 游乐园 梦幻 童话 城堡 carousel' },
  { id: 'fireworks', label: '绚烂烟火', category: '夜空盛典', tone: 'yellow', group: 'milestones', keywords: '烟花 烟火 跨年 盛典 夜空 浪漫 庆祝 fireworks' },
  { id: 'airballoon', label: '梦幻热气球', category: '高空飞行', tone: 'pink', group: 'travel', keywords: '热气球 飞行 土耳其 浪漫 俯瞰 日出 balloon' },
  { id: 'aquarium', label: '深海海洋馆', category: '梦幻场馆', tone: 'blue', group: 'travel', keywords: '海洋馆 水族馆 鲸鱼 企鹅 隧道 蓝色 aquarium' },
  { id: 'museum', label: '艺术博览馆', category: '文艺漫步', tone: 'yellow', group: 'growth', keywords: '博物馆 美术馆 展览 文物 历史 漫步 museum' },
  { id: 'planetarium', label: '梦幻天文馆', category: '星空漫步', tone: 'blue', group: 'travel', keywords: '天文馆 穹顶 星空 宇宙 银河 望远镜 planetarium' },
  { id: 'picnic', label: '草地野餐', category: '户外休闲', tone: 'pink', group: 'travel', keywords: '野餐 草坪 阳光 野餐垫 三明治 春天 picnic' },
  { id: 'sunset', label: '橘子日落', category: '自然景观', tone: 'yellow', group: 'travel', keywords: '日落 黄昏 晚霞 海边 橘子海 浪漫 sunset' },
  { id: 'hotspring', label: '暖冬温泉', category: '休闲疗愈', tone: 'blue', group: 'travel', keywords: '温泉 泡汤 冬天 疗愈 暖和 舒缓 hot spring' },
  { id: 'skiing', label: '雪原滑雪', category: '冰雪运动', tone: 'blue', group: 'travel', keywords: '滑雪 雪场 双板 单板 冬天 雪山 ski' },
  { id: 'surfing', label: '夏日冲浪', category: '水上运动', tone: 'blue', group: 'travel', keywords: '冲浪 海滩 浪花 夏天 阳光 运动 surf' },
  { id: 'stargazing', label: '露营看星', category: '夜空观测', tone: 'yellow', group: 'travel', keywords: '星空 露营 观星 流星 银河 帐篷 stars' },
  { id: 'cablecar', label: '观光缆车', category: '山川巡游', tone: 'yellow', group: 'travel', keywords: '缆车 索道 登山 俯瞰 景区 观光 cable car' },
  { id: 'lighthouse', label: '海岸灯塔', category: '向海而行', tone: 'blue', group: 'travel', keywords: '灯塔 海边 指引 守望 蔚蓝 海洋 lighthouse' },
  { id: 'island', label: '度假海岛', category: '海岛度假', tone: 'yellow', group: 'travel', keywords: '海岛 椰树 沙滩 度假 阳光 碧海 island' },
  { id: 'temple', label: '祈福古刹', category: '心愿祈福', tone: 'yellow', group: 'milestones', keywords: '古寺 祈福 许愿 寺庙 抽签 钟声 temple' },
  { id: 'waterfall', label: '幽谷瀑布', category: '山水秘境', tone: 'blue', group: 'travel', keywords: '瀑布 飞瀑 清凉 徒步 山谷 避暑 waterfall' },
  { id: 'safari', label: '野趣探险', category: '动物探索', tone: 'yellow', group: 'travel', keywords: '野生动物 动物园 吉普 巡游 探险 safari' },
  { id: 'fountain', label: '许愿喷泉', category: '浪漫祈愿', tone: 'blue', group: 'travel', keywords: '喷泉 许愿池 硬币 欧式 广场 罗马 fountain' },

  // 41-60: 节日纪念与浪漫仪式
  { id: 'ring', label: '相守钻戒', category: '永恒誓言', tone: 'blue', group: 'milestones', keywords: '钻戒 戒指 求婚 结婚 订婚 承诺 誓言 ring' },
  { id: 'letter', label: '手写情书', category: '纸短情长', tone: 'pink', group: 'milestones', keywords: '情书 信件 慢递 见字如面 手写 纸条 letter' },
  { id: 'bouquet', label: '心动花束', category: '浪漫告白', tone: 'pink', group: 'milestones', keywords: '花束 郁金香 玫瑰 鲜花 告白 惊喜 bouquet' },
  { id: 'candle', label: '香薰烛光', category: '烛光氛围', tone: 'yellow', group: 'daily', keywords: '蜡烛 烛光 香薰 晚餐 氛围 浪漫 candle' },
  { id: 'toast', label: '香槟碰杯', category: '欢聚庆贺', tone: 'yellow', group: 'milestones', keywords: '碰杯 香槟 庆祝 节日 干杯 喜悦 toast cheer' },
  { id: 'cal_love', label: '甜蜜日历', category: '专属纪念', tone: 'pink', group: 'milestones', keywords: '纪念日 日历 倒计时 恋爱 百天 周年 calendar' },
  { id: 'key', label: '新家钥匙', category: '爱巢启程', tone: 'yellow', group: 'milestones', keywords: '钥匙 新家 同居 搬家 入住 门锁 key' },
  { id: 'heart_lock', label: '同心爱锁', category: '永恒誓言', tone: 'pink', group: 'milestones', keywords: '爱心锁 同心锁 连理 约定 誓言 lock' },
  { id: 'origami', label: '祈愿千纸鹤', category: '温柔祝福', tone: 'blue', group: 'daily', keywords: '折纸 千纸鹤 祈愿 心愿 祝福 手工 origami' },
  { id: 'snowglobe', label: '梦幻雪花球', category: '冬日童话', tone: 'blue', group: 'milestones', keywords: '水晶球 水晶 八音盒 飘雪 圣诞 梦境 globe' },
  { id: 'polaroid', label: '定格拍立得', category: '影像定格', tone: 'yellow', group: 'daily', keywords: '拍立得 照片 定格 相机 即影 瞬间 polaroid' },
  { id: 'ribbon', label: '礼物丝带', category: '惊喜包装', tone: 'pink', group: 'milestones', keywords: '丝带 蝴蝶结 包装 礼盒 惊喜 心意 ribbon' },
  { id: 'melodybox', label: '发条八音盒', category: '岁月轻音', tone: 'yellow', group: 'milestones', keywords: '八音盒 音乐盒 发条 旋律 怀旧 复古 melodybox' },
  { id: 'chime', label: '清脆风铃', category: '夏日微风', tone: 'blue', group: 'daily', keywords: '风铃 夏天 檐下 微风 叮咚 清凉 chime' },
  { id: 'lantern', label: '元宵花灯', category: '传统佳节', tone: 'pink', group: 'milestones', keywords: '花灯 灯笼 元宵 中秋 团圆 挂灯 lantern' },
  { id: 'luckybag', label: '吉祥福袋', category: '好运随行', tone: 'pink', group: 'milestones', keywords: '福袋 好运 新年 祈福 幸运 顺遂 lucky bag' },
  { id: 'wishstar', label: '幸运许愿星', category: '心愿收藏', tone: 'yellow', group: 'milestones', keywords: '许愿瓶 玻璃瓶 叠星星 心愿 祝福 star' },
  { id: 'firefly', label: '夏夜微光', category: '幽夜浪漫', tone: 'yellow', group: 'daily', keywords: '萤火虫 夏夜 微光 森林 浪漫 追光 firefly' },
  { id: 'rainbow', label: '晴日彩虹', category: '美好奇迹', tone: 'blue', group: 'travel', keywords: '彩虹 雨过天晴 幸运 奇迹 七彩 晴朗 rainbow' },
  { id: 'clover', label: '幸运四叶草', category: '幸运守护', tone: 'green', group: 'growth', keywords: '四叶草 幸运 奇迹 守护 绿意 幸运儿 clover' },

  // 61-80: 文艺娱乐与兴趣爱好
  { id: 'guitar', label: '温暖吉他', category: '弹唱时光', tone: 'yellow', group: 'growth', keywords: '吉他 民谣 弹唱 弹琴 音乐 弦乐 guitar' },
  { id: 'piano', label: '黑白琴键', category: '优雅律动', tone: 'blue', group: 'growth', keywords: '钢琴 琴键 乐曲 优雅 演奏 练习 piano' },
  { id: 'easel', label: '灵感画架', category: '写意丹青', tone: 'yellow', group: 'growth', keywords: '画架 油画 绘画 采风 写生 画板 easel' },
  { id: 'palette', label: '多彩画盘', category: '创意涂鸦', tone: 'yellow', group: 'growth', keywords: '调色盘 水彩 涂鸦 颜料 艺术 创作 palette' },
  { id: 'pottery', label: '泥陶手作', category: '慢调工艺', tone: 'yellow', group: 'growth', keywords: '陶艺 拉胚 泥塑 手作 工坊 陶瓷 pottery' },
  { id: 'vinyl', label: '黑胶回响', category: '复古听觉', tone: 'pink', group: 'growth', keywords: '黑胶 唱片 复古 留声机 慢时光 音乐 vinyl' },
  { id: 'cassette', label: '复古磁带', category: '怀旧之声', tone: 'blue', group: 'growth', keywords: '磁带 卡带 随身听 怀旧 歌单 磁头 cassette' },
  { id: 'arcade', label: '怀旧街机', category: '双人激战', tone: 'lilac', group: 'growth', keywords: '街机 摇杆 电玩城 游戏 投币 双人 arcade' },
  { id: 'bowling', label: '全中保龄球', category: '动感竞技', tone: 'blue', group: 'growth', keywords: '保龄球 全中 运动 球道 比赛 击倒 bowling' },
  { id: 'badminton', label: '羽球挥拍', category: '活力对决', tone: 'yellow', group: 'growth', keywords: '羽毛球 扣杀 运动 挥拍 健身 双打 badminton' },
  { id: 'skateboard', label: '追风滑板', category: '街头自由', tone: 'yellow', group: 'growth', keywords: '滑板 街头 刷街 动作 自由 滑行 skateboard' },
  { id: 'dice', label: '聚会桌游', category: '策略博弈', tone: 'pink', group: 'growth', keywords: '骰子 桌游 聚会 游戏 投掷 运气 dice' },
  { id: 'theater', label: '剧场话剧', category: '文艺舞台', tone: 'yellow', group: 'growth', keywords: '话剧 戏剧 面具 舞台 音乐剧 观剧 theater' },
  { id: 'gardening', label: '阳台莳花', category: '自然绿植', tone: 'green', group: 'growth', keywords: '园艺 种花 浇水 阳台 绿植 盆栽 gardening' },
  { id: 'knitting', label: '温情编织', category: '手作温暖', tone: 'pink', group: 'growth', keywords: '织毛衣 毛线 针织 围巾 手作 温暖 knitting' },
  { id: 'telescope', label: '深空望远镜', category: '宇宙凝望', tone: 'blue', group: 'growth', keywords: '望远镜 观星 月球 行星 探索 宇宙 telescope' },
  { id: 'microphone', label: '欢唱麦克风', category: 'K歌狂欢', tone: 'yellow', group: 'growth', keywords: '麦克风 唱歌 KTV 欢唱 练歌 演唱 microphone' },
  { id: 'swimming', label: '泳池畅游', category: '清凉戏水', tone: 'pink', group: 'growth', keywords: '游泳 泳圈 玩水 泳池 夏天 戏水 swimming' },
  { id: 'yoga', label: '舒展瑜伽', category: '身心觉知', tone: 'lilac', group: 'growth', keywords: '瑜伽 冥想 舒展 拉伸 平静 身心 yoga' },
  { id: 'reading', label: '书香墨卷', category: '静心阅己', tone: 'blue', group: 'growth', keywords: '读书 看书 借书 书店 咖啡 独处 reading' },

  // 81-100: 生活治愈与温馨日常
  { id: 'alarm', label: '晨光闹铃', category: '朝夕作息', tone: 'pink', group: 'daily', keywords: '闹钟 早起 早安 准时 起床 时间 alarm' },
  { id: 'slippers', label: '情侣软拖', category: '居家温柔', tone: 'blue', group: 'daily', keywords: '拖鞋 棉拖 居家 温暖 室内 贴心 slippers' },
  { id: 'sofa', label: '双人沙发', category: '居家乐居', tone: 'green', group: 'daily', keywords: '沙发 客厅 窝着 追剧 放松 惬意 sofa' },
  { id: 'plant', label: '多肉萌植', category: '窗台生机', tone: 'green', group: 'daily', keywords: '多肉 窗台 绿植 浇水 治愈 盆栽 succulent plant' },
  { id: 'mug', label: '默契对杯', category: '晨昏热饮', tone: 'pink', group: 'daily', keywords: '马克杯 对杯 喝水 热茶 咖啡 温热 mug' },
  { id: 'umbrella', label: '同乘雨伞', category: '风雨同舟', tone: 'yellow', group: 'daily', keywords: '雨伞 撑伞 下雨 雨天 避雨 依偎 umbrella' },
  { id: 'bathtub', label: '泡泡浴缸', category: '卸下疲惫', tone: 'blue', group: 'daily', keywords: '浴缸 泡澡 泡泡 小黄鸭 放松 消除疲劳 bath' },
  { id: 'pillow', label: '云朵软枕', category: '安然酣眠', tone: 'pink', group: 'daily', keywords: '抱枕 靠垫 枕头 软绵绵 靠背 依赖 pillow' },
  { id: 'laundry', label: '晴空晒衣', category: '阳光气息', tone: 'blue', group: 'daily', keywords: '晾衣 晒衣服 阳光 洗衣 阳台 清新 laundry' },
  { id: 'mirror', label: '相映立镜', category: '对镜梳妆', tone: 'blue', group: 'daily', keywords: '穿衣镜 镜子 照镜子 梳妆 出门 仪容 mirror' },
  { id: 'window', label: '明净朝窗', category: '透亮晴岚', tone: 'blue', group: 'daily', keywords: '窗户 窗外 晨光 晴天 窗台 通风 window' },
  { id: 'teapot', label: '温润茶壶', category: '午后茶话', tone: 'pink', group: 'food', keywords: '茶壶 泡茶 沏茶 红茶 茶歇 慢生活 teapot' },
  { id: 'honey', label: '金黄甘蜜', category: '甘甜滋味', tone: 'yellow', group: 'food', keywords: '蜂蜜 甜 蜂巢 柠檬水 调味 润燥 honey' },
  { id: 'cookie', label: '焦香曲奇', category: '手作烘焙', tone: 'yellow', group: 'food', keywords: '曲奇 饼干 烘焙 巧克力豆 零食 酥脆 cookie' },
  { id: 'jam', label: '馥郁果酱', category: '果味封存', tone: 'pink', group: 'food', keywords: '果酱 草莓酱 抹面包 甜 早餐 吐司 jam' },
  { id: 'sunflower', label: '向阳花开', category: '热烈生命', tone: 'yellow', group: 'daily', keywords: '向日葵 太阳花 金黄 阳光 灿烂 盛开 sunflower' },
  { id: 'tulip', label: '优雅郁金香', category: '淡雅芳菲', tone: 'pink', group: 'daily', keywords: '郁金香 优雅 粉白 鲜花 花期 赏花 tulip' },
  { id: 'match', label: '微光火柴', category: '点燃温暖', tone: 'yellow', group: 'daily', keywords: '火柴 火苗 点燃 取暖 微光 烛火 match' },
  { id: 'luggage', label: '启程行李箱', category: '整理行囊', tone: 'yellow', group: 'travel', keywords: '行李箱 拉杆箱 旅行 出发 收纳 登机 luggage' },
  { id: 'ticket', label: '同往票根', category: '珍藏票据', tone: 'pink', group: 'milestones', keywords: '门票 票根 电影票 车票 留念 见证 ticket' },
] as const
export type EventArtId = (typeof eventArtOptions)[number]['id']
// Keep the existing DB field and CHECK length. Old emoji values render as SVG;
// new choices store stable identifiers, never executable markup or URLs.
const legacy: Record<string, EventArtId> = {
  '💛': 'heart',
  '♥': 'heart',
  '💗': 'heart',
  '🌊': 'sea',
  '🎂': 'cake',
  '🚃': 'train',
  '✈️': 'plane',
  '🎓': 'trophy',
  '🎄': 'tree',
  '🏠': 'home',
}
export function eventArtId(value: string): EventArtId {
  const id = value.replace(/^icon:/, '')
  return eventArtOptions.find((option) => option.id === id)?.id || legacy[value] || 'heart'
}
export function eventArtConfig(value: string) {
  return eventArtOptions.find((option) => option.id === eventArtId(value))!
}

export function filterEventArt(group: EventArtGroup, query: string) {
  const words = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)
  return eventArtOptions.filter((option) => {
    const text =
      `${option.label} ${option.category} ${option.keywords} ${option.id}`.toLocaleLowerCase()
    return (group === 'all' || option.group === group) && words.every((word) => text.includes(word))
  })
}
