export const eventArtGroups = [
  { id: 'all', label: '全部' },
  { id: 'friends', label: '小伙伴' },
  { id: 'daily', label: '恋爱日常' },
  { id: 'travel', label: '旅行自然' },
  { id: 'milestones', label: '节日纪念' },
  { id: 'growth', label: '成长目标' },
] as const
export type EventArtGroup = (typeof eventArtGroups)[number]['id']

export const eventArtOptions = [
  {
    id: 'heart',
    label: '恋爱心动',
    category: '恋爱纪念',
    tone: 'pink',
    group: 'daily',
    keywords: '喜欢 爱情 表白 love',
  },
  {
    id: 'bunny',
    label: '送信小兔',
    category: '想见你',
    tone: 'pink',
    group: 'friends',
    keywords: '兔子 兔兔 rabbit bunny',
  },
  {
    id: 'dog',
    label: '出游小狗',
    category: '一起出发',
    tone: 'yellow',
    group: 'friends',
    keywords: '狗狗 小狗 puppy dog',
  },
  {
    id: 'cat',
    label: '橘子小猫',
    category: '猫系陪伴',
    tone: 'yellow',
    group: 'friends',
    keywords: '猫咪 橘猫 cat',
  },
  {
    id: 'bear',
    label: '抱抱小熊',
    category: '温柔拥抱',
    tone: 'yellow',
    group: 'friends',
    keywords: '熊熊 玩偶 bear',
  },
  {
    id: 'penguin',
    label: '围巾企鹅',
    category: '暖暖陪伴',
    tone: 'blue',
    group: 'friends',
    keywords: '企鹅 冬天 penguin',
  },
  {
    id: 'fox',
    label: '机灵狐狸',
    category: '小小冒险',
    tone: 'yellow',
    group: 'friends',
    keywords: '狐狸 小狐 fox',
  },
  {
    id: 'frog',
    label: '快乐青蛙',
    category: '元气满满',
    tone: 'green',
    group: 'friends',
    keywords: '青蛙 蛙蛙 frog',
  },
  {
    id: 'duck',
    label: '散步小鸭',
    category: '一起散步',
    tone: 'yellow',
    group: 'friends',
    keywords: '鸭子 小鸭 duck',
  },
  {
    id: 'cake',
    label: '生日蛋糕',
    category: '生日快乐',
    tone: 'lilac',
    group: 'milestones',
    keywords: '生日 蛋糕 庆祝 cake birthday',
  },
  {
    id: 'sea',
    label: '海边假期',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '看海 沙滩 度假 sea beach',
  },
  {
    id: 'train',
    label: '见面列车',
    category: '奔向彼此',
    tone: 'green',
    group: 'travel',
    keywords: '高铁 火车 见面 train',
  },
  {
    id: 'plane',
    label: '旅行飞机',
    category: '一起旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '飞机 旅游 出国 plane flight',
  },
  {
    id: 'trophy',
    label: '里程奖杯',
    category: '特别里程',
    tone: 'yellow',
    group: 'milestones',
    keywords: '成就 奖杯 纪念 trophy',
  },
  {
    id: 'gift',
    label: '惊喜礼物',
    category: '小小惊喜',
    tone: 'pink',
    group: 'milestones',
    keywords: '礼物 送礼 惊喜 gift',
  },
  {
    id: 'coffee',
    label: '咖啡约会',
    category: '日常约会',
    tone: 'green',
    group: 'daily',
    keywords: '咖啡 奶茶 饮料 coffee',
  },
  {
    id: 'tree',
    label: '节日小树',
    category: '节日约定',
    tone: 'green',
    group: 'milestones',
    keywords: '圣诞 节日 树 christmas',
  },
  {
    id: 'home',
    label: '一起回家',
    category: '共同生活',
    tone: 'yellow',
    group: 'daily',
    keywords: '新家 搬家 同居 home',
  },
  {
    id: 'book',
    label: '一起读书',
    category: '共同成长',
    tone: 'blue',
    group: 'growth',
    keywords: '学习 考试 考研 阅读 读书 book study',
  },
  {
    id: 'briefcase',
    label: '工作加油',
    category: '工作目标',
    tone: 'yellow',
    group: 'growth',
    keywords: '工作 入职 实习 转正 work job',
  },
  {
    id: 'code',
    label: '编程搭子',
    category: '一起创造',
    tone: 'green',
    group: 'growth',
    keywords: '编程 代码 项目 coding code',
  },
  {
    id: 'flag',
    label: '目标达成',
    category: '一起冲刺',
    tone: 'pink',
    group: 'growth',
    keywords: '考试 考研 目标 计划 flag goal',
  },
  {
    id: 'dumbbell',
    label: '运动打卡',
    category: '健康陪伴',
    tone: 'blue',
    group: 'growth',
    keywords: '健身 运动 肌肉 训练 gym fitness',
  },
  {
    id: 'bicycle',
    label: '周末骑行',
    category: '运动出游',
    tone: 'green',
    group: 'growth',
    keywords: '单车 自行车 骑行 bike cycling',
  },
  {
    id: 'camera',
    label: '拍照留念',
    category: '收藏瞬间',
    tone: 'lilac',
    group: 'daily',
    keywords: '摄影 相机 合照 写真 camera photo',
  },
  {
    id: 'music',
    label: '音乐现场',
    category: '一起听歌',
    tone: 'pink',
    group: 'daily',
    keywords: '音乐 演唱会 歌曲 concert music',
  },
  {
    id: 'headphone',
    label: '共享耳机',
    category: '同频时刻',
    tone: 'blue',
    group: 'daily',
    keywords: '听歌 耳机 播客 headphone',
  },
  {
    id: 'gamepad',
    label: '双人游戏',
    category: '快乐双排',
    tone: 'lilac',
    group: 'daily',
    keywords: '游戏 手柄 双排 game',
  },
  {
    id: 'movie',
    label: '电影之夜',
    category: '一起观影',
    tone: 'yellow',
    group: 'daily',
    keywords: '电影 影院 追剧 movie film',
  },
  {
    id: 'shopping',
    label: '逛街约会',
    category: '日常约会',
    tone: 'pink',
    group: 'daily',
    keywords: '购物 逛街 买衣服 shopping',
  },
  {
    id: 'flower',
    label: '送你小花',
    category: '浪漫日常',
    tone: 'pink',
    group: 'daily',
    keywords: '花朵 鲜花 花束 flower',
  },
  {
    id: 'icecream',
    label: '冰淇淋日',
    category: '甜甜日常',
    tone: 'lilac',
    group: 'daily',
    keywords: '冰激凌 冰淇淋 甜品 ice cream',
  },
  {
    id: 'sun',
    label: '一起看日出',
    category: '晴天出游',
    tone: 'yellow',
    group: 'travel',
    keywords: '日出 太阳 晴天 sun sunrise',
  },
  {
    id: 'moon',
    label: '月亮晚安',
    category: '月下约定',
    tone: 'blue',
    group: 'travel',
    keywords: '月亮 晚安 星夜 moon night',
  },
  {
    id: 'mountain',
    label: '一起爬山',
    category: '山野出游',
    tone: 'green',
    group: 'travel',
    keywords: '爬山 登山 远足 mountain hiking',
  },
  {
    id: 'tent',
    label: '星空露营',
    category: '户外约定',
    tone: 'green',
    group: 'travel',
    keywords: '露营 帐篷 户外 tent camping',
  },
  {
    id: 'compass',
    label: '探索地图',
    category: '一起冒险',
    tone: 'yellow',
    group: 'travel',
    keywords: '指南针 探索 导航 compass',
  },
  {
    id: 'backpack',
    label: '背包出发',
    category: '周末旅行',
    tone: 'blue',
    group: 'travel',
    keywords: '背包 远行 旅行 backpack trip',
  },
  {
    id: 'star',
    label: '闪闪发光',
    category: '特别时刻',
    tone: 'yellow',
    group: 'milestones',
    keywords: '星星 星光 成就 star',
  },
  {
    id: 'balloon',
    label: '庆祝气球',
    category: '快乐庆祝',
    tone: 'pink',
    group: 'milestones',
    keywords: '气球 聚会 派对 balloon party',
  },
] as const
export type EventArtId = (typeof eventArtOptions)[number]['id']
// Keep the existing DB field and CHECK length. Old emoji values render as SVG;
// new choices store stable identifiers, never executable markup or URLs.
const legacy: Record<string, EventArtId> = {
  '💛': 'heart',
  '♥': 'heart',
  '💗': 'heart',
  '🌊': 'sea',
  '🎂': 'cake',
  '🚃': 'train',
  '✈️': 'plane',
  '🎓': 'trophy',
  '🎄': 'tree',
  '🏠': 'home',
}
export function eventArtId(value: string): EventArtId {
  const id = value.replace(/^icon:/, '')
  return eventArtOptions.find((option) => option.id === id)?.id || legacy[value] || 'heart'
}
export function eventArtConfig(value: string) {
  return eventArtOptions.find((option) => option.id === eventArtId(value))!
}

export function filterEventArt(group: EventArtGroup, query: string) {
  const words = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)
  return eventArtOptions.filter((option) => {
    const text =
      `${option.label} ${option.category} ${option.keywords} ${option.id}`.toLocaleLowerCase()
    return (group === 'all' || option.group === group) && words.every((word) => text.includes(word))
  })
}
