import type { Space } from './types'
import { togetherDays } from './dates'

export type MilestoneCategory = 'all' | 'days' | 'photos' | 'events' | 'interaction'

export interface Milestone {
  id: string
  category: 'days' | 'photos' | 'events' | 'interaction'
  name: string
  art: string
  color: string
  target: number
  unit: string
  current: number
  reached: boolean
  reachedDesc: string
  waitingDesc: string
}

export function buildMilestones(space: Space, now = new Date()): Milestone[] {
  const days = space.couple?.together_since ? togetherDays(space.couple.together_since, now) : 0
  const photosCount = space.photos?.length || 0
  const eventsCount = space.events?.length || 0
  const messagesCount = space.messages?.length || 0
  const pingsCount = space.pings?.length || 0

  const myAvatar = space.me?.avatar || 'dog'
  const partnerAvatar = space.partner?.avatar || 'bunny'

  return [
    // --- 1. 相伴时光 (Days) ---
    {
      id: 'days-100',
      category: 'days',
      name: '100 天心动',
      art: 'heart',
      color: 'yellow',
      target: 100,
      unit: '天',
      current: days,
      reached: days >= 100,
      reachedDesc: '又多了一份关于我们的回忆',
      waitingDesc: `还差 ${100 - days} 天，一起慢慢来`,
    },
    {
      id: 'days-365',
      category: 'days',
      name: '一周年纪念',
      art: partnerAvatar,
      color: 'pink',
      target: 365,
      unit: '天',
      current: days,
      reached: days >= 365,
      reachedDesc: '走过四季轮转，依然最喜欢你',
      waitingDesc: `还差 ${365 - days} 天，期待周年那一天`,
    },
    {
      id: 'days-520',
      category: 'days',
      name: '520 我爱你',
      art: myAvatar,
      color: 'mint',
      target: 520,
      unit: '天',
      current: days,
      reached: days >= 520,
      reachedDesc: '平凡日子里的心动暗号',
      waitingDesc: `还差 ${520 - days} 天，继续深爱`,
    },
    {
      id: 'days-730',
      category: 'days',
      name: '两载春秋',
      art: 'cake',
      color: 'peach',
      target: 730,
      unit: '天',
      current: days,
      reached: days >= 730,
      reachedDesc: '两年朝夕相伴，温柔且笃定',
      waitingDesc: `还差 ${730 - days} 天，两周年倒计时`,
    },
    {
      id: 'days-999',
      category: 'days',
      name: '天长地久',
      art: 'star',
      color: 'gold',
      target: 999,
      unit: '天',
      current: days,
      reached: days >= 999,
      reachedDesc: '长长久久，胜过万千繁星',
      waitingDesc: `还差 ${999 - days} 天，向着久久前行`,
    },
    {
      id: 'days-1000',
      category: 'days',
      name: '千日长相守',
      art: 'trophy',
      color: 'lavender',
      target: 1000,
      unit: '天',
      current: days,
      reached: days >= 1000,
      reachedDesc: '破千日的相守，最珍贵的誓约',
      waitingDesc: `还差 ${1000 - days} 天，一起破千日`,
    },
    {
      id: 'days-1314',
      category: 'days',
      name: '一生一世',
      art: 'crown',
      color: 'rose',
      target: 1314,
      unit: '天',
      current: days,
      reached: days >= 1314,
      reachedDesc: '一生一世的浪漫守护',
      waitingDesc: `还差 ${1314 - days} 天，一生一世的约定`,
    },
    {
      id: 'days-1500',
      category: 'days',
      name: '岁月成诗',
      art: 'flower',
      color: 'butter',
      target: 1500,
      unit: '天',
      current: days,
      reached: days >= 1500,
      reachedDesc: '一千五百个晨昏，把日子过成诗',
      waitingDesc: `还差 ${1500 - days} 天，岁月静好`,
    },
    {
      id: 'days-1825',
      category: 'days',
      name: '五载深情',
      art: 'gem',
      color: 'sky',
      target: 1825,
      unit: '天',
      current: days,
      reached: days >= 1825,
      reachedDesc: '五周年携手，山高水长一路同行',
      waitingDesc: `还差 ${1825 - days} 天，向五周年靠近`,
    },
    {
      id: 'days-2000',
      category: 'days',
      name: '两千日月',
      art: 'tree',
      color: 'cyan',
      target: 2000,
      unit: '天',
      current: days,
      reached: days >= 2000,
      reachedDesc: '根深叶茂，爱意已长成参天大树',
      waitingDesc: `还差 ${2000 - days} 天，两千天的守候`,
    },
    {
      id: 'days-2500',
      category: 'days',
      name: '漫漫同行',
      art: 'compass',
      color: 'orange',
      target: 2500,
      unit: '天',
      current: days,
      reached: days >= 2500,
      reachedDesc: '无论身在何方，你就是我的方向',
      waitingDesc: `还差 ${2500 - days} 天，步履不停`,
    },
    {
      id: 'days-3000',
      category: 'days',
      name: '三千繁花',
      art: 'sparkles',
      color: 'lilac',
      target: 3000,
      unit: '天',
      current: days,
      reached: days >= 3000,
      reachedDesc: '弱水三千，繁花如锦，只取一瓢',
      waitingDesc: `还差 ${3000 - days} 天，三千日的传奇`,
    },

    // --- 2. 独家回忆 (Photos / Memories) ---
    {
      id: 'photos-1',
      category: 'photos',
      name: '初次定格',
      art: 'camera',
      color: 'sky',
      target: 1,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 1,
      reachedDesc: '第一声快门，心动有了画面',
      waitingDesc: `已记录 ${photosCount}/1 张，去上传第一张合照吧`,
    },
    {
      id: 'photos-5',
      category: 'photos',
      name: '生活剪影',
      art: 'sun',
      color: 'orange',
      target: 5,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 5,
      reachedDesc: '散落人间的小美好，我们一一珍藏',
      waitingDesc: `已记录 ${photosCount}/5 张回忆，继续拍照吧`,
    },
    {
      id: 'photos-15',
      category: 'photos',
      name: '甜蜜映画',
      art: 'balloon',
      color: 'pink',
      target: 15,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 15,
      reachedDesc: '十五个精彩瞬间，连成了电影',
      waitingDesc: `已记录 ${photosCount}/15 张回忆，期待下一次同框`,
    },
    {
      id: 'photos-30',
      category: 'photos',
      name: '时光胶囊',
      art: 'gift',
      color: 'butter',
      target: 30,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 30,
      reachedDesc: '把回忆封存，随时取出一份甜',
      waitingDesc: `已记录 ${photosCount}/30 张回忆，胶囊正在填满`,
    },
    {
      id: 'photos-50',
      category: 'photos',
      name: '专属相册',
      art: 'party',
      color: 'mint',
      target: 50,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 50,
      reachedDesc: '半百张胶片，写满彼此眼里的光',
      waitingDesc: `已记录 ${photosCount}/50 张回忆，相册越来越厚啦`,
    },
    {
      id: 'photos-100',
      category: 'photos',
      name: '银幕百景',
      art: 'gem',
      color: 'gold',
      target: 100,
      unit: '张',
      current: photosCount,
      reached: photosCount >= 100,
      reachedDesc: '百张定格，属于我们俩的纪录大片',
      waitingDesc: `已记录 ${photosCount}/100 张回忆，百张大关冲刺`,
    },

    // --- 3. 心愿约定 (Events) ---
    {
      id: 'events-1',
      category: 'events',
      name: '最初的约定',
      art: 'gift',
      color: 'yellow',
      target: 1,
      unit: '个',
      current: eventsCount,
      reached: eventsCount >= 1,
      reachedDesc: '种下一个小愿望，一起期待它开花',
      waitingDesc: `已记录 ${eventsCount}/1 个约定，添加第一个期待吧`,
    },
    {
      id: 'events-3',
      category: 'events',
      name: '美好启程',
      art: 'compass',
      color: 'cyan',
      target: 3,
      unit: '个',
      current: eventsCount,
      reached: eventsCount >= 3,
      reachedDesc: '出发吧，有你同行处处是风景',
      waitingDesc: `已记录 ${eventsCount}/3 个约定，期待每一次同行`,
    },
    {
      id: 'events-5',
      category: 'events',
      name: '携手并肩',
      art: 'backpack',
      color: 'lavender',
      target: 5,
      unit: '个',
      current: eventsCount,
      reached: eventsCount >= 5,
      reachedDesc: '清单上的一件件小事，都是幸福证据',
      waitingDesc: `已记录 ${eventsCount}/5 个约定，心愿慢慢实现`,
    },
    {
      id: 'events-10',
      category: 'events',
      name: '心愿地图',
      art: 'map',
      color: 'mint',
      target: 10,
      unit: '个',
      current: eventsCount,
      reached: eventsCount >= 10,
      reachedDesc: '十个共同约定，铺满未来的轨迹',
      waitingDesc: `已记录 ${eventsCount}/10 个约定，心愿地图渐显`,
    },
    {
      id: 'events-20',
      category: 'events',
      name: '漫游世界',
      art: 'plane',
      color: 'rose',
      target: 20,
      unit: '个',
      current: eventsCount,
      reached: eventsCount >= 20,
      reachedDesc: '星辰大海，我们要手牵手慢慢看遍',
      waitingDesc: `已记录 ${eventsCount}/20 个约定，写满浪漫篇章`,
    },

    // --- 4. 双向奔赴 (Messages & Pings) ---
    {
      id: 'messages-10',
      category: 'interaction',
      name: '初次私语',
      art: 'mail',
      color: 'peach',
      target: 10,
      unit: '条',
      current: messagesCount,
      reached: messagesCount >= 10,
      reachedDesc: '只有彼此听得见的轻声细语',
      waitingDesc: `已发送 ${messagesCount}/10 条悄悄话，去说说心里话吧`,
    },
    {
      id: 'messages-99',
      category: 'interaction',
      name: '碎碎念念',
      art: 'coffee',
      color: 'orange',
      target: 99,
      unit: '条',
      current: messagesCount,
      reached: messagesCount >= 99,
      reachedDesc: '分享欲是最高级的浪漫告白',
      waitingDesc: `已发送 ${messagesCount}/99 条悄悄话，碎碎念也是爱`,
    },
    {
      id: 'messages-520',
      category: 'interaction',
      name: '字字深情',
      art: 'book',
      color: 'pink',
      target: 520,
      unit: '条',
      current: messagesCount,
      reached: messagesCount >= 520,
      reachedDesc: '字里行间，全都是你',
      waitingDesc: `已发送 ${messagesCount}/520 条悄悄话，写满520句爱意`,
    },
    {
      id: 'messages-1314',
      category: 'interaction',
      name: '万语倾心',
      art: 'sparkles',
      color: 'gold',
      target: 1314,
      unit: '条',
      current: messagesCount,
      reached: messagesCount >= 1314,
      reachedDesc: '千言万语，都不及你在身边',
      waitingDesc: `已发送 ${messagesCount}/1314 条悄悄话，一生倾心`,
    },
    {
      id: 'pings-1',
      category: 'interaction',
      name: '心动信号',
      art: 'bell',
      color: 'yellow',
      target: 1,
      unit: '次',
      current: pingsCount,
      reached: pingsCount >= 1,
      reachedDesc: '哔卟！一次轻轻的呼唤与回应',
      waitingDesc: `已发送 ${pingsCount}/1 次呼唤，去轻触呼唤 TA 吧`,
    },
    {
      id: 'pings-20',
      category: 'interaction',
      name: '思念回响',
      art: 'headphone',
      color: 'sky',
      target: 20,
      unit: '次',
      current: pingsCount,
      reached: pingsCount >= 20,
      reachedDesc: '跨越距离的每一次震动，都是在说想你',
      waitingDesc: `已发送 ${pingsCount}/20 次呼唤，常常呼唤彼此`,
    },
    {
      id: 'pings-100',
      category: 'interaction',
      name: '心跳同频',
      art: 'music',
      color: 'lavender',
      target: 100,
      unit: '次',
      current: pingsCount,
      reached: pingsCount >= 100,
      reachedDesc: '百次心电感应，彼此心意从不失联',
      waitingDesc: `已发送 ${pingsCount}/100 次呼唤，百次默契同频`,
    },
  ]
}

export function getNextWaitingMilestone(milestones: Milestone[]): Milestone | undefined {
  return milestones.find((m) => !m.reached)
}
