import type { WardrobeItem } from './types'

export const WARDROBE_ITEMS: WardrobeItem[] = [
  // ================= 衣服 (Clothes: 21 件) =================
  {
    id: 'c_blue_hoodie',
    name: '经典蓝卫衣',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_blue_hoodie',
    metadata: { tag: '日常百搭', couplePairId: 'c_pink_hoodie' },
  },
  {
    id: 'c_pink_hoodie',
    name: '甜蜜粉卫衣',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_pink_hoodie',
    metadata: { tag: '情侣心动', couplePairId: 'c_blue_hoodie' },
  },
  {
    id: 'c_striped_tee',
    name: '条纹海魂衫',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_striped_tee',
    metadata: { tag: '清凉夏日' },
  },
  {
    id: 'c_sailor_suit',
    name: '青春水手服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_sailor_suit',
    metadata: { tag: '校园青葱' },
  },
  {
    id: 'c_british_blazer',
    name: '英伦小制服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_british_blazer',
    metadata: { tag: '学院优雅' },
  },
  {
    id: 'c_overalls',
    name: '工装牛仔裤',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_overalls',
    metadata: { tag: '工装复古' },
  },
  {
    id: 'c_white_shirt',
    name: '纯白衬衫',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_white_shirt',
    metadata: { tag: '简约干练' },
  },
  {
    id: 'c_christmas_sweater',
    name: '圣诞红毛衣',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_christmas_sweater',
    metadata: { tag: '节日温暖' },
  },
  {
    id: 'c_winter_down_jacket',
    name: '暖冬羽绒服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_winter_down_jacket',
    metadata: { tag: '御寒蓬松' },
  },
  {
    id: 'c_hawaiian_shirt',
    name: '夏威夷衬衫',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_hawaiian_shirt',
    metadata: { tag: '海岛度假' },
  },
  {
    id: 'c_sports_jersey',
    name: '运动活力校服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_sports_jersey',
    metadata: { tag: '青春运动' },
  },
  {
    id: 'c_detective_cape',
    name: '侦探小风衣',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_detective_cape',
    metadata: { tag: '推理密友' },
  },
  {
    id: 'c_chef_apron',
    name: '烘焙小围裙',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_chef_apron',
    metadata: { tag: '温馨厨艺' },
  },
  {
    id: 'c_magic_robe',
    name: '魔法长袍',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_magic_robe',
    metadata: { tag: '奇幻魔法' },
  },
  {
    id: 'c_cozy_pajamas',
    name: '草莓睡袍',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_cozy_pajamas',
    metadata: { tag: '居家舒适' },
  },
  {
    id: 'c_space_suit',
    name: '星际宇航服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_space_suit',
    metadata: { tag: '漫游太空' },
  },
  {
    id: 'c_couple_mint_tee',
    name: '薄荷情侣T恤',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_couple_mint_tee',
    metadata: { tag: '薄荷清新', couplePairId: 'c_couple_lilac_tee' },
  },
  {
    id: 'c_couple_lilac_tee',
    name: '香芋情侣T恤',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_couple_lilac_tee',
    metadata: { tag: '温柔紫罗兰', couplePairId: 'c_couple_mint_tee' },
  },
  {
    id: 'c_knitted_vest',
    name: '学院麻花背心',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_knitted_vest',
    metadata: { tag: '温润书卷' },
  },
  {
    id: 'c_kimono_robe',
    name: '和风浴衣',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_kimono_robe',
    metadata: { tag: '花火物语' },
  },
  {
    id: 'c_party_tuxedo',
    name: '庆典燕尾服',
    category: 'clothes',
    layer: 'clothes',
    anchor: 'body',
    offset: { x: 0, y: 0 },
    assetId: 'asset_c_party_tuxedo',
    metadata: { tag: '盛典盛装' },
  },

  // ================= 帽子 (Hats: 21 件) =================
  {
    id: 'h_red_beret',
    name: '复古红贝雷帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_red_beret',
    metadata: { tag: '文艺浪漫', couplePairId: 'h_black_beret' },
  },
  {
    id: 'h_black_beret',
    name: '优雅黑贝雷帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_black_beret',
    metadata: { tag: '低调雅致', couplePairId: 'h_red_beret' },
  },
  {
    id: 'h_baseball_cap',
    name: '动感棒球帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_baseball_cap',
    metadata: { tag: '街头运动' },
  },
  {
    id: 'h_bucket_hat',
    name: '嫩黄渔夫帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_bucket_hat',
    metadata: { tag: '元气遮阳' },
  },
  {
    id: 'h_santa_hat',
    name: '经典圣诞帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_santa_hat',
    metadata: { tag: '圣诞快乐' },
  },
  {
    id: 'h_deer_antlers',
    name: '萌鹿角发箍',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    // 鹿角需要干净的头顶空间：长耳/大耳角色会与耳朵穿模
    characterOverrides: {
      bunny: { visible: false },
      chinchilla: { visible: false },
    },
    assetId: 'asset_h_deer_antlers',
    metadata: { tag: '灵动鹿角' },
  },
  {
    id: 'h_flower_crown',
    name: '春日雏菊花环',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_flower_crown',
    metadata: { tag: '烂漫繁花' },
  },
  {
    id: 'h_pink_bow',
    name: '甜心蝴蝶结',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_pink_bow',
    metadata: { tag: '粉嫩甜美', couplePairId: 'h_mint_bow' },
  },
  {
    id: 'h_mint_bow',
    name: '薄荷蝴蝶结',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_mint_bow',
    metadata: { tag: '清爽薄荷', couplePairId: 'h_pink_bow' },
  },
  {
    id: 'h_gold_crown',
    name: '闪亮小金冠',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_gold_crown',
    metadata: { tag: '高贵小国王' },
  },
  {
    id: 'h_cat_ears',
    name: '萌系猫耳发箍',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    // 长耳/大耳/耳羽角色戴猫耳发箍会出现四只耳朵的杂乱构图
    characterOverrides: {
      bunny: { visible: false },
      chinchilla: { visible: false },
      owl: { visible: false },
    },
    assetId: 'asset_h_cat_ears',
    metadata: { tag: '傲娇猫咪' },
  },
  {
    id: 'h_duck_beanie',
    name: '小鸭毛线帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_duck_beanie',
    metadata: { tag: '嘎嘎保暖' },
  },
  {
    id: 'h_winter_beanie',
    name: '暖冬雪花冷帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_winter_beanie',
    metadata: { tag: '冬季防寒' },
  },
  {
    id: 'h_chef_toque',
    name: '烘焙主厨高帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_chef_toque',
    metadata: { tag: '星级大厨' },
  },
  {
    id: 'h_magic_wizard_hat',
    name: '魔法尖顶帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_magic_wizard_hat',
    metadata: { tag: '奥秘巫师' },
  },
  {
    id: 'h_detective_hat',
    name: '侦探格纹帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_detective_hat',
    metadata: { tag: '神探出场' },
  },
  {
    id: 'h_straw_sunhat',
    name: '草编遮阳帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_straw_sunhat',
    metadata: { tag: '海滩漫步' },
  },
  {
    id: 'h_pajama_nightcap',
    name: '软绵垂坠睡帽',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_pajama_nightcap',
    metadata: { tag: '美梦晚安' },
  },
  {
    id: 'h_space_helmet',
    name: '宇航透明面罩',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_space_helmet',
    metadata: { tag: '深空探索' },
  },
  {
    id: 'h_heart_antenna',
    name: '心动爱心天线',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_heart_antenna',
    metadata: { tag: '心动感应' },
  },
  {
    id: 'h_sprout_hairclip',
    name: '头顶发芽小草',
    category: 'hats',
    layer: 'hat',
    anchor: 'head',
    offset: { x: 0, y: 0 },
    assetId: 'asset_h_sprout_hairclip',
    metadata: { tag: '呆萌发芽' },
  },

  // ================= 配饰 (Accessories: 21 件) =================
  {
    id: 'a_heart_balloon',
    name: '心形红气球',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_heart_balloon',
    metadata: { tag: '浪漫飞扬' },
  },
  {
    id: 'a_polaroid_camera',
    name: '拍立得相机',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_polaroid_camera',
    metadata: { tag: '定格瞬间' },
  },
  {
    id: 'a_sunflower',
    name: '向日葵花束',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_sunflower',
    metadata: { tag: '向阳灿烂' },
  },
  {
    id: 'a_boba_milk_tea',
    name: '波霸珍珠奶茶',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_boba_milk_tea',
    metadata: { tag: '半糖去冰' },
  },
  {
    id: 'a_crossbody_bag',
    name: '明黄小挎包',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_crossbody_bag',
    metadata: { tag: '随身便携' },
  },
  {
    id: 'a_school_backpack',
    name: '学霸双肩包',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'back',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_school_backpack',
    metadata: { tag: '认真上学' },
  },
  {
    id: 'a_red_scarf',
    name: '暖红毛线围巾',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: 0, y: 0 },
    // 企鹅/仓鼠基础立绘自带围巾或围嘴，再叠围巾会出现双层穿模
    characterOverrides: {
      penguin: { visible: false },
      hamster: { visible: false },
    },
    assetId: 'asset_a_red_scarf',
    metadata: { tag: '温暖缠绕' },
  },
  {
    id: 'a_magic_wand',
    name: '星光魔法杖',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_magic_wand',
    metadata: { tag: '心愿成真' },
  },
  {
    id: 'a_love_letter',
    name: '心动告白信',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_love_letter',
    metadata: { tag: '纸短情长' },
  },
  {
    id: 'a_detective_magnifier',
    name: '侦探放大镜',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_detective_magnifier',
    metadata: { tag: '发现破绽' },
  },
  {
    id: 'a_whisk_spoon',
    name: '烘焙打蛋勺',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_whisk_spoon',
    metadata: { tag: '甜点制作' },
  },
  {
    id: 'a_beach_swim_ring',
    name: '小鸭游泳圈',
    category: 'accessories',
    layer: 'accessory',
    // 环身道具吸附腰部，避免勒在脖子/脸上
    anchor: 'waist',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_beach_swim_ring',
    metadata: { tag: '夏日嬉水' },
  },
  {
    id: 'a_star_badge',
    name: '荣誉星徽章',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_star_badge',
    metadata: { tag: '闪耀功勋' },
  },
  {
    id: 'a_gold_medal',
    name: '第一名金牌',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_gold_medal',
    metadata: { tag: '全场最佳' },
  },
  {
    id: 'a_coffee_cup',
    name: '暖心外带热咖啡',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_coffee_cup',
    metadata: { tag: '醇香提神' },
  },
  {
    id: 'a_toast_mouth',
    name: '晨间小吐司',
    category: 'accessories',
    layer: 'accessory',
    // 口部道具：逐角色 mouth 锚点（嘴/喙中心）保证"咬住"成立
    anchor: 'mouth',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_toast_mouth',
    metadata: { tag: '咬住赶路' },
  },
  {
    id: 'a_gameboy',
    name: '掌上像素机',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'hand',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_gameboy',
    metadata: { tag: '复古游戏' },
  },
  {
    id: 'a_cherry_pin',
    name: '双生樱桃胸针',
    category: 'accessories',
    layer: 'accessory',
    anchor: 'front',
    offset: { x: -6, y: -2 },
    assetId: 'asset_a_cherry_pin',
    metadata: { tag: '酸甜小果' },
  },
  {
    id: 'a_sparkle_aura',
    name: '闪烁心动光效',
    category: 'accessories',
    layer: 'special',
    anchor: 'accessory',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_sparkle_aura',
    metadata: { tag: '全屏闪耀' },
  },
  {
    id: 'a_ghost_companion',
    name: '萌萌小幽灵跟宠',
    category: 'accessories',
    layer: 'special',
    anchor: 'accessory',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_ghost_companion',
    metadata: { tag: '漂浮跟宠' },
  },
  {
    id: 'a_musical_notes',
    name: '欢快律动音符',
    category: 'accessories',
    layer: 'special',
    anchor: 'accessory',
    offset: { x: 0, y: 0 },
    assetId: 'asset_a_musical_notes',
    metadata: { tag: '轻快歌唱' },
  },
]

export const WARDROBE_MAP: Record<string, WardrobeItem> = WARDROBE_ITEMS.reduce(
  (acc, item) => {
    acc[item.id] = item
    return acc
  },
  {} as Record<string, WardrobeItem>,
)

export const CLOTHES_LIST = WARDROBE_ITEMS.filter((i) => i.category === 'clothes')
export const HATS_LIST = WARDROBE_ITEMS.filter((i) => i.category === 'hats')
export const ACCESSORIES_LIST = WARDROBE_ITEMS.filter((i) => i.category === 'accessories')
